---
# common tasks for skeletons
# child of: `flarum.yml`, `mediawiki.yml`, `wordpress.yml`
# params:
#   - skeleton_root_dir: root directory of the skeleton

- name: Create required directories for {{ skeleton_root_dir }}
  ansible.builtin.file:
      state: "directory"
      path: "{{ skeleton_root_dir }}/{{ php_dir }}"
      owner: www-data
      group: www-data
      mode: "775"
      recurse: true
  loop:
      - "app"
      - "bin"
      - "dev"
      - "etc/ssl/certs"
      - "session"
      - "tmp"
      - "usr/bin"
      - "usr/sbin"
      - "usr/lib/{{ ansible_architecture }}-linux-gnu"
      - "usr/lib/postfix" # for sendmail postfix libraries
      - "usr/share/zoneinfo"
  loop_control:
      loop_var: "php_dir"
  tags: [always]

- name: Create dev files
  ansible.builtin.command:
      cmd: "mknod -m {{ dev_file.mode }} {{ skeleton_root_dir }}/dev/{{ dev_file.name }} {{ dev_file.type }} {{ dev_file.major }} {{ dev_file.minor }}"
      creates: "{{ skeleton_root_dir }}/dev/{{ dev_file.name }}"
  become: true
  loop:
      - name: "null"
        type: "c"
        major: 1
        minor: 3
        mode: "666"
      - name: "zero"
        type: "c"
        major: 1
        minor: 5
        mode: "666"
      - name: "full"
        type: "c"
        major: 1
        minor: 7
        mode: "666"
      - name: "random"
        type: "c"
        major: 1
        minor: 8
        mode: "444"
      - name: "urandom"
        type: "c"
        major: 1
        minor: 9
        mode: "444"
      - name: "tty"
        type: "c"
        major: 5
        minor: 0
        mode: "666"
      - name: "console"
        type: "c"
        major: 5
        minor: 1
        mode: "600"
      - name: "ptmx"
        type: "c"
        major: 5
        minor: 2
        mode: "666"
  loop_control:
      loop_var: "dev_file"
  tags: [always]

- name: Create hardlinks for required system files
  ansible.builtin.file:
      src: "{{ php_hardlink.src }}"
      dest: "{{ php_hardlink.dest }}"
      state: hard
      mode: "755"
  loop:
      - src: "/etc/ssl/certs/ca-certificates.crt"
        dest: "{{ skeleton_root_dir }}/etc/ssl/certs/ca-certificates.crt"
      - src: "/usr/lib/{{ ansible_architecture }}-linux-gnu/ld-linux-{{ ansible_architecture }}.so.1"
        dest: "{{ skeleton_root_dir }}/usr/lib/{{ ansible_architecture }}-linux-gnu/ld-linux-{{ ansible_architecture }}.so.1"
      - src: "/usr/lib/{{ ansible_architecture }}-linux-gnu/libc.so.6"
        dest: "{{ skeleton_root_dir }}/usr/lib/{{ ansible_architecture }}-linux-gnu/libc.so.6"
      - src: "/usr/lib/{{ ansible_architecture }}-linux-gnu/libnss_dns.so.2"
        dest: "{{ skeleton_root_dir }}/usr/lib/{{ ansible_architecture }}-linux-gnu/libnss_dns.so.2"
      - src: "/usr/lib/{{ ansible_architecture }}-linux-gnu/ld-linux-aarch64.so.1"
        dest: "{{ skeleton_root_dir }}/usr/lib/{{ ansible_architecture }}-linux-gnu/ld-linux-aarch64.so.1"

      - src: "/usr/sbin/sendmail"
        dest: "{{ skeleton_root_dir }}/usr/sbin/sendmail"
      - src: "/usr/bin/bash"
        dest: "{{ skeleton_root_dir }}/usr/bin/bash"
      - src: "/usr/bin/dash"
        dest: "{{ skeleton_root_dir }}/usr/bin/dash"
  loop_control:
      loop_var: php_hardlink
  tags: [always]

- name: Create canonical hardlink for libtinfo
  ansible.builtin.include_tasks: canonical_hardlink.yml
  vars:
      hardlink_src: "/usr/lib/{{ ansible_architecture }}-linux-gnu/libtinfo.so.6"
      hardlink_dest: "{{ skeleton_root_dir }}/usr/lib/{{ ansible_architecture }}-linux-gnu/libtinfo.so.6"
      hardlink_root_dir: "{{ skeleton_root_dir }}"

- name: Create symlinks
  ansible.builtin.file:
      src: "{{ php_symlink.src }}"
      path: "{{ php_symlink.path }}"
      owner: www-data
      group: www-data
      force: true
      follow: false
      state: link
  loop:
      # relative paths for chroot
      - src: "app/public"
        path: "{{ skeleton_root_dir }}/public"
      - src: "usr/bin"
        path: "{{ skeleton_root_dir }}/bin"
      - src: "usr/sbin"
        path: "{{ skeleton_root_dir }}/sbin"
      - src: "usr/lib"
        path: "{{ skeleton_root_dir }}/lib"
      - src: "usr/lib/{{ ansible_architecture }}-linux-gnu/ld-linux-aarch64.so.1"
        path: "{{ skeleton_root_dir }}/usr/lib/ld-linux-aarch64.so.1"
  loop_control:
      loop_var: php_symlink
  tags: [always]

- name: Recursively hardlink zoneinfo
  ansible.posix.synchronize:
      src: /usr/share/zoneinfo/
      dest: "{{ skeleton_root_dir }}/usr/share/zoneinfo"
      rsync_opts:
          - "--link-dest=/usr/share/zoneinfo"
  delegate_to: "{{ inventory_hostname }}"
  tags: [always]
