[Service]
Restart=always
RestartSec=10
TimeoutStartSec=10m
TimeoutStopSec=10m

LimitNOFILE=infinity
LimitMEMLOCK=infinity

PrivateTmp=true
ProtectSystem=full
ReadWritePaths=/run/php /var/log/php {{ paths.tenants.root }}
NoNewPrivileges=true
ProtectKernelTunables=true
ProtectKernelModules=true
ProtectControlGroups=true
RestrictRealtime=true
RestrictNamespaces=true
LockPersonality=true
RestrictAddressFamilies=AF_INET AF_INET6 AF_UNIX
