[Service]
Restart=always    
RestartSec=10

LimitNOFILE=infinity
LimitMEMLOCK=infinity

PrivateTmp=true
ProtectSystem=full
NoNewPrivileges=true
ProtectKernelTunables=true
ProtectKernelModules=true
ProtectControlGroups=true
RestrictRealtime=true
RestrictNamespaces=true
LockPersonality=true
MemoryDenyWriteExecute=true
RestrictAddressFamilies=AF_INET AF_INET6 AF_UNIX
SystemCallFilter=~@privileged @resources

[Install]
Alias=php-fpm.service
