prefix = {{ paths.tenants.root }}/$pool
chroot = {{ paths.tenants.root }}/$pool
chdir = /

user = tenant_$pool
group = tenant_$pool

listen = /run/php/php-fpm.$pool.sock
listen.group = www-data
listen.owner = tenant_$pool
listen.mode = 0660

pm = ondemand
pm.max_children = 50
pm.process_idle_timeout = 10s
pm.max_requests = 500


catch_workers_output = yes
php_admin_value[session_save_path] = sessions
php_admin_value[error_log] = logs/php-fpm.log
