chroot = {{ paths.tenants.root }}/$pool
prefix = {{ paths.tenants.root }}/$pool/public
chdir = /

user = tenant_$pool
group = tenant_$pool

process.priority = 19
process.dumpable = no

listen = /run/php/php-fpm.$pool.sock
listen.group = www-data
listen.owner = tenant_$pool
listen.mode = 0660

pm = ondemand
pm.max_children = 50
pm.process_idle_timeout = 10s
pm.max_requests = 500

catch_workers_output = yes
php_admin_value[error_log] = logs/php-fpm.log


php_admin_value[doc_root] = /public
php_admin_value[cgi.fix_pathinfo] = 0
php_admin_flag[expose_php] = Off

php_admin_value[include_path] = .
php_admin_value[open_basedir] = /etc/config.json:/app/:/tmp:/session:/dev/urandom
php_admin_value[sys_temp_dir] = /tmp
php_admin_value[upload_tmp_dir] = /tmp
php_admin_value[session.save_path] = /session
php_admin_value[sendmail_path] = /usr/sbin/sendmail -f -i
php_admin_value[openssl.capath] = /etc/ssl/certs
