[global]
pid = /run/php/php-fpm.pid
error_log = /var/log/php/fpm.log

emergency_restart_threshold = 10
emergency_restart_interval = 1m
process_control_timeout = 10s

rlimit_files = 32768
include=/etc/php/fpm/pool.d/*

; minimal placeholder pool to satisfy php-fpm's "at least 1 pool" requirement
; this pool is never actually used, it just allows PHP-FPM to start
; before any tenant pools are created.
[-]
user = nobody
group = nogroup
listen = /run/php/_
listen.owner = nobody
listen.group = nogroup
listen.mode = 0000
pm = ondemand
pm.max_children = 1

