map "$host:$canonical_host" $needs_redirect {
    "~^(.+):\1$"   "";     # host == canonical_host, no redirect
    "~^.+:$"       "";     # canonical_host empty, no redirect
    "~^.+:.+$"     "yes";  # host differs, needs redirect
    default "";
}
