# hostnames -> site_id
map $host $site_id {
    hostnames;

    # internal hosts
    # flarum_skeleton.no-cost.forum     flarum_skeleton;
    # flarum_skeleton.no-cost.wiki      flarum_skeleton;
    # flarum_skeleton.no-cost.site      flarum_skeleton;

    # user domains/CNAMEs
    # example.com  mysite;

    default "";
}

# site_id -> canonical hostname
map $site_id $canonical_host {
    # flarum_skeleton     flarum_skeleton.no-cost.forum;
    # mysite              example.com;

    default "";
}

# site_id -> service type
map $site_id $service_type {
    # flarum_skeleton     flarum;
    # mediawiki_skeleton  mediawiki;
    # wordpress_skeleton  wordpress;

    default "";
}
