# canonical hostname -> site_id
map $host $site_id {
    hostnames;

    # internal canonical hosts
    # flarum_skeleton.no-cost.forum     flarum_skeleton;
    # mediawiki_skeleton.no-cost.wiki   mediawiki_skeleton;
    # wordpress_skeleton.no-cost.site   wordpress_skeleton;

    # user domains/CNAMEs
    # example.com  mysite;

    default "";
}

# site_id -> service type
map $site_id $service_type {
    # flarum_skeleton     flarum;
    # mediawiki_skeleton  mediawiki;
    # wordpress_skeleton  wordpress;

    default "";
}