# wildcard for internal domains,
# letsencrypt for user domains
map $ssl_server_name $ssl_cert_dir {
{% for domain in domains.keys() %}
    ~^(.+\.)?{{ domain | regex_escape }}$ /etc/ssl/wildcard/{{ domain }};
{% endfor %}
    default /etc/letsencrypt/live/$ssl_server_name;
}
