---
- name: Configure UFW defaults
  ansible.builtin.copy:
      src: files/etc/default/ufw
      dest: /etc/default/ufw
      mode: "0644"
  tags: ["security"]

- name: Configure UFW rules
  community.general.ufw:
      rule: allow
      port: "{{ port }}"
      proto: tcp
  loop: "{{ ufw_allowed_ports }}"
  loop_control:
      loop_var: port
  tags: ["security"]

- name: Enable UFW
  community.general.ufw:
      state: enabled
      policy: deny
      direction: incoming
  tags: ["security"]

- name: Configure fail2ban for SSH
  ansible.builtin.copy:
      src: files/etc/fail2ban/jail.local
      dest: /etc/fail2ban/jail.local
      mode: "0644"
  notify: restart fail2ban
  tags: ["security"]

# https://rkhunter.sourceforge.net/
- name: Set up rkhunter
  ansible.builtin.apt:
      name: rkhunter
      state: present
  tags: ["security"]

- name: Configure rkhunter
  ansible.builtin.copy:
      src: files/etc/rkhunter.conf
      dest: /etc/rkhunter.conf
      mode: "0644"
  tags: ["security"]

# https://aide.github.io/
- name: Set up AIDE (Advanced Intrusion Detection Environment)
  ansible.builtin.apt:
      name: aide
      state: present
  tags: ["security"]

- name: Initialize AIDE database
  ansible.builtin.command:
      cmd: aideinit
      creates: /var/lib/aide/aide.db
  tags: ["security"]
