---
- name: Install Nginx
  ansible.builtin.apt:
      name: nginx
      state: present

- name: Remove default Nginx site
  ansible.builtin.file:
      path: "{{ item }}"
      state: absent
  loop:
      - /etc/nginx/sites-enabled/default
      - /etc/nginx/sites-available

- name: Ensure Nginx cache and log directories exist
  ansible.builtin.file:
      path: "{{ item }}"
      state: directory
      mode: "755"
      owner: root
      group: root
  loop:
      - /var/cache/nginx
      - /var/log/nginx

- name: Ensure Nginx subdirectories exist
  ansible.builtin.file:
      path: "{{ item }}"
      state: directory
      mode: "0755"
  loop:
      - /etc/nginx/sites-available
      - /etc/nginx/sites-enabled
      - /etc/nginx/snippets

- name: Process Nginx configuration templates
  ansible.builtin.template:
      src: "files{{ item }}"
      dest: "{{ item }}"
      mode: "0644"
  loop:
      - /etc/nginx/nginx.conf
      - /etc/nginx/sites-enabled/dynamic.conf
      - /etc/nginx/sites-enabled/main-site.conf
      - /etc/nginx/snippets/gzip.conf
      - /etc/nginx/snippets/rate-limits.conf
      - /etc/nginx/snippets/security-headers.conf
      - /etc/nginx/snippets/ssl-params.conf
  notify: reload nginx

- name: Start Nginx service
  ansible.builtin.systemd:
      name: nginx
      enabled: true
      state: started
      daemon_reload: true

# https://linux.die.net/man/8/logrotate
- name: Set up log rotation for Nginx
  ansible.builtin.copy:
      src: files/etc/logrotate.d/nginx
      dest: /etc/logrotate.d/nginx
      mode: "644"

- name: Restart Nginx
  ansible.builtin.systemd:
      name: nginx
      state: restarted
