---
- name: Install Nginx
  ansible.builtin.apt:
      name: nginx
      state: present
  tags: ["nginx", "web"]

- name: Remove default Nginx sites
  ansible.builtin.file:
      path: "{{ nginx_path }}"
      state: absent
  loop:
      - /etc/nginx/sites-enabled/default
      - /etc/nginx/sites-available
  loop_control:
      loop_var: nginx_path
  tags: ["nginx", "web"]

- name: Ensure Nginx directories exist
  ansible.builtin.file:
      path: "{{ item.path }}"
      state: directory
      mode: "{{ item.mode }}"
      owner: "{{ item.owner }}"
      group: "{{ item.group }}"
  loop:
      - path: /var/cache/nginx
        owner: root
        group: root
        mode: "0755"
      - path: /var/log/nginx
        owner: root
        group: root
        mode: "0755"
      - path: /etc/nginx/sites-available
        owner: www-data
        group: www-data
        mode: "0755"
      - path: /etc/nginx/sites-enabled
        owner: www-data
        group: www-data
        mode: "0755"
      - path: /etc/nginx/snippets
        owner: www-data
        group: www-data
        mode: "0755"
      - path: /etc/nginx/maps
        owner: www-data
        group: www-data
        mode: "0755"
      - path: /etc/nginx/service-rules
        owner: www-data
        group: www-data
        mode: "0755"
      - path: /var/run/nginx
        owner: www-data
        group: www-data
        mode: "0755"
  tags: ["nginx", "web"]

- name: Fetch Cloudflare IPv4 ranges
  ansible.builtin.uri:
      url: https://www.cloudflare.com/ips-v4
      return_content: true
  register: cloudflare_ipv4_response
  tags: ["nginx", "web"]

- name: Fetch Cloudflare IPv6 ranges
  ansible.builtin.uri:
      url: https://www.cloudflare.com/ips-v6
      return_content: true
  register: cloudflare_ipv6_response
  tags: ["nginx", "web"]

- name: Set Cloudflare IP facts
  ansible.builtin.set_fact:
      cloudflare_ips_v4: "{{ cloudflare_ipv4_response.content.split('\n') | select }}"
      cloudflare_ips_v6: "{{ cloudflare_ipv6_response.content.split('\n') | select }}"
  tags: ["nginx", "web"]

- name: Template Cloudflare realip config
  ansible.builtin.template:
      src: files/etc/nginx/snippets/cloudflare-realip.conf
      dest: /etc/nginx/snippets/cloudflare-realip.conf
      mode: "0644"
  notify: reload nginx
  tags: ["nginx", "web"]

- name: Process Nginx configuration templates
  ansible.builtin.template:
      src: "files{{ nginx_conf }}"
      dest: "{{ nginx_conf }}"
      mode: "0644"
  loop:
      - /etc/nginx/nginx.conf
      - /etc/nginx/maps/sites.conf
      - /etc/nginx/maps/ssl.conf
      - /etc/nginx/sites-enabled/dynamic.conf
      - /etc/nginx/sites-enabled/main-site.conf
      - /etc/nginx/snippets/gzip.conf
      - /etc/nginx/snippets/log-format.conf
      - /etc/nginx/snippets/rate-limits.conf
      - /etc/nginx/snippets/security-headers.conf
      - /etc/nginx/snippets/ssl-params.conf
      - /etc/nginx/snippets/tenant-common.conf
  loop_control:
      loop_var: nginx_conf
  notify: reload nginx
  tags: ["nginx", "web"]

- name: Copy all service-specific Nginx rules
  ansible.builtin.copy:
      src: "files/etc/nginx/apps/"
      dest: /etc/nginx/apps/
      mode: "0644"
  notify: reload nginx
  tags: ["nginx", "web"]

# https://linux.die.net/man/8/logrotate
- name: Set up log rotation for Nginx
  ansible.builtin.copy:
      src: files/etc/logrotate.d/nginx
      dest: /etc/logrotate.d/nginx
      mode: "644"
  tags: ["nginx", "web"]

- name: Restart Nginx
  ansible.builtin.systemd:
      name: nginx
      enabled: true
      state: restarted
  tags: ["nginx", "web"]
