---
- name: Install Nginx
  ansible.builtin.apt:
      name: nginx
      state: present
  tags: ["nginx", "web"]

- name: Remove default Nginx site
  ansible.builtin.file:
      path: "{{ nginx_path }}"
      state: absent
  loop:
      - /etc/nginx/sites-enabled/default
      - /etc/nginx/sites-available
  loop_control:
      loop_var: nginx_path
  tags: ["nginx", "web"]

- name: Ensure Nginx cache and log directories exist
  ansible.builtin.file:
      path: "{{ nginx_log_path }}"
      state: directory
      mode: "755"
      owner: root
      group: root
  loop:
      - /var/cache/nginx
      - /var/log/nginx
  loop_control:
      loop_var: nginx_log_path
  tags: ["nginx", "web"]

- name: Ensure Nginx subdirectories exist
  ansible.builtin.file:
      path: "{{ nginx_subdir }}"
      state: directory
      mode: "0755"
  loop:
      - /etc/nginx/sites-available
      - /etc/nginx/sites-enabled
      - /etc/nginx/snippets
  loop_control:
      loop_var: nginx_subdir
  tags: ["nginx", "web"]

- name: Fetch Cloudflare IPv4 ranges
  ansible.builtin.uri:
      url: https://www.cloudflare.com/ips-v4
      return_content: true
  register: cloudflare_ipv4_response
  tags: ["nginx", "web"]

- name: Fetch Cloudflare IPv6 ranges
  ansible.builtin.uri:
      url: https://www.cloudflare.com/ips-v6
      return_content: true
  register: cloudflare_ipv6_response
  tags: ["nginx", "web"]

- name: Set Cloudflare IP facts
  ansible.builtin.set_fact:
      cloudflare_ips_v4: "{{ cloudflare_ipv4_response.content.split('\n') | select }}"
      cloudflare_ips_v6: "{{ cloudflare_ipv6_response.content.split('\n') | select }}"
  tags: ["nginx", "web"]

- name: Template Cloudflare realip config
  ansible.builtin.template:
      src: files/etc/nginx/snippets/cloudflare-realip.conf
      dest: /etc/nginx/snippets/cloudflare-realip.conf
      mode: "0644"
  notify: reload nginx
  tags: ["nginx", "web"]

- name: Process Nginx configuration templates
  ansible.builtin.template:
      src: "files{{ nginx_conf }}"
      dest: "{{ nginx_conf }}"
      mode: "0644"
  loop:
      - /etc/nginx/nginx.conf
      - /etc/nginx/sites-enabled/dynamic.conf
      - /etc/nginx/sites-enabled/main-site.conf
      - /etc/nginx/snippets/gzip.conf
      - /etc/nginx/snippets/log-format.conf
      - /etc/nginx/snippets/rate-limits.conf
      - /etc/nginx/snippets/security-headers.conf
      - /etc/nginx/snippets/ssl-params.conf
  loop_control:
      loop_var: nginx_conf
  notify: reload nginx
  tags: ["nginx", "web"]

- name: Start Nginx service
  ansible.builtin.systemd:
      name: nginx
      enabled: true
      state: started
      daemon_reload: true
  tags: ["nginx", "web"]

# https://linux.die.net/man/8/logrotate
- name: Set up log rotation for Nginx
  ansible.builtin.copy:
      src: files/etc/logrotate.d/nginx
      dest: /etc/logrotate.d/nginx
      mode: "644"
  tags: ["nginx", "web"]

- name: Restart Nginx
  ansible.builtin.systemd:
      name: nginx
      state: restarted
  tags: ["nginx", "web"]
