---
- name: Add PHP repository
  ansible.builtin.apt_repository:
      repo: "ppa:ondrej/php"
      state: present
      update_cache: true

- name: Install PHP-FPM and extensions
  ansible.builtin.apt:
      name:
          - "php{{ php_version }}-fpm"
          - "php{{ php_version }}-cli"
          - "php{{ php_version }}-common"
          - "php{{ php_version }}-mysql"
          - "php{{ php_version }}-sqlite3"
          - "php{{ php_version }}-xml"
          - "php{{ php_version }}-curl"
          - "php{{ php_version }}-gd"
          - "php{{ php_version }}-imagick"
          - "php{{ php_version }}-mbstring"
          - "php{{ php_version }}-zip"
          - "php{{ php_version }}-bcmath"
          - "php{{ php_version }}-intl"
          - "php{{ php_version }}-opcache"
          - "php{{ php_version }}-readline"
          - "php{{ php_version }}-ldap"
          - "php{{ php_version }}-exif"
      state: present

- name: Symlink configuration directory
  ansible.builtin.file:
      src: /etc/php/fpm/{{ php_version }}
      dest: /etc/php/fpm
      state: link
      force: true

- name: Configure PHP-FPM
  ansible.builtin.template:
      src: "files{{ item }}"
      dest: "{{ item }}"
      mode: "644"
  loop:
      - /etc/php/fpm/php-fpm.conf
      - /etc/php/fpm/php.ini
      - /etc/php/fpm/generic-pool.conf
  notify: restart php-fpm

- name: Remove default www pool
  ansible.builtin.file:
      path: "/etc/php/fpm/pool.d/www.conf"
      state: absent

- name: Configure PHP-FPM systemd override for security
  ansible.builtin.copy:
      src: playbooks/files/etc/systemd/system/php-fpm.service.d/override.conf
      dest: "/etc/systemd/system/php{{ php_version }}-fpm.service.d/override.conf"
      mode: "644"
  notify:
      - daemon reload
      - restart php-fpm

- name: Create PHP-FPM log directory
  ansible.builtin.file:
      path: /var/log/php
      state: directory
      owner: www-data
      group: www-data
      mode: "755"

- name: Configure OPcache for production
  ansible.builtin.copy:
      src: files/etc/php/mods-available/opcache.ini
      dest: /etc/php/mods-available/opcache.ini
      mode: "644"
  notify: restart php-fpm

- name: Start and enable PHP-FPM service
  ansible.builtin.systemd:
      name: "php{{ php_version }}-fpm"
      enabled: true
      state: started
      daemon_reload: true
