---
- name: Download MariaDB repository setup script
  ansible.builtin.get_url:
      url: https://r.mariadb.com/downloads/mariadb_repo_setup
      dest: /tmp/mariadb_repo_setup
      mode: "0755"
  tags: ["mariadb", "database"]

- name: Setup MariaDB 11.8 repository
  ansible.builtin.command:
      cmd: "/tmp/mariadb_repo_setup --mariadb-server-version={{ ('mariadb-' + mariadb_version) | quote }}"
      creates: /etc/apt/sources.list.d/mariadb.list
  tags: ["mariadb", "database"]

- name: Remove mariadb_repo_setup tmp file
  ansible.builtin.file:
      path: /tmp/mariadb_repo_setup
      state: absent
  tags: ["mariadb", "database"]

- name: Update apt cache after adding MariaDB repository
  ansible.builtin.apt:
      update_cache: true
  tags: ["mariadb", "database"]

- name: Install MariaDB
  ansible.builtin.apt:
      name:
          - mariadb-server
          - mariadb-client
          - python3-pymysql
      state: present
  tags: ["mariadb", "database"]

- name: Ensure MySQL log directory exists
  ansible.builtin.file:
      path: /var/log/mysql
      state: directory
      owner: mysql
      group: adm
      mode: "750"
  tags: ["mariadb", "database"]

- name: Configure MariaDB for production
  ansible.builtin.template:
      src: files/etc/mysql/mariadb.conf.d/50-server.cnf
      dest: /etc/mysql/mariadb.conf.d/50-server.cnf
      mode: "644"
  notify: restart mariadb
  tags: ["mariadb", "database"]

- name: Ensure MariaDB override directory exists
  ansible.builtin.file:
      path: /etc/systemd/system/mariadb.service.d
      state: directory
      mode: "644"
  tags: ["mariadb", "database"]

- name: Set MariaDB systemd limits
  ansible.builtin.copy:
      src: files/etc/systemd/system/mariadb.service.d/limits.conf
      dest: /etc/systemd/system/mariadb.service.d/limits.conf
      mode: "644"
  tags: ["mariadb", "database"]

- name: Ensure MariaDB is running
  ansible.builtin.systemd:
      name: mariadb
      enabled: true
      state: restarted
      daemon_reload: true
  tags: ["mariadb", "database"]

- name: Configure root user for socket authentication
  community.mysql.mysql_user:
      name: root
      plugin: unix_socket
      plugin_auth_string: ""
      host: localhost
      login_unix_socket: /run/mysqld/mysqld.sock
      column_case_sensitive: true
      state: present
  tags: ["mariadb", "database"]

- name: Remove anonymous MySQL users
  community.mysql.mysql_user:
      name: ""
      host_all: true
      login_unix_socket: /run/mysqld/mysqld.sock
      column_case_sensitive: true
      state: absent
  tags: ["mariadb", "database"]

- name: Remove MySQL test database
  community.mysql.mysql_db:
      name: test
      login_unix_socket: /run/mysqld/mysqld.sock
      state: absent
  tags: ["mariadb", "database"]

- name: Ensure databases for services
  community.mysql.mysql_db:
      name: nocost
      encoding: utf8mb4
      collation: utf8mb4_unicode_ci
      login_unix_socket: /run/mysqld/mysqld.sock
      state: present
  tags: ["mariadb", "database"]

- name: Ensure MySQL backup user
  community.mysql.mysql_user:
      name: backup
      plugin: unix_socket
      plugin_auth_string: ""
      priv: "*.*:SELECT,LOCK TABLES,SHOW VIEW,EVENT,TRIGGER"
      host: localhost
      login_unix_socket: /run/mysqld/mysqld.sock
      column_case_sensitive: true
      state: present
  tags: ["mariadb", "database"]

- name: Configure log rotation for MariaDB
  ansible.builtin.copy:
      src: files/etc/logrotate.d/mariadb
      dest: /etc/logrotate.d/mariadb
      mode: "644"
  tags: ["mariadb", "database"]
