---
- name: Get available memory
  ansible.builtin.setup:
      gather_subset:
          - hardware
      filter: ansible_memtotal_mb

- name: Install MariaDB
  ansible.builtin.apt:
      name:
          - mariadb-server
          - mariadb-client
          - python3-pymysql
      state: present

- name: Configure MariaDB for production
  ansible.builtin.template:
      src: files/etc/mysql/mariadb.conf.d/50-server.cnf
      dest: /etc/mysql/mariadb.conf.d/50-server.cnf
      mode: "644"
  notify: restart mariadb

- name: Ensure MariaDB override directory exists
  ansible.builtin.file:
      path: /etc/systemd/system/mariadb.service.d
      state: directory
      mode: "644"

- name: Set MariaDB systemd limits
  ansible.builtin.copy:
      src: files/etc/systemd/system/mariadb.service.d/limits.conf
      dest: /etc/systemd/system/mariadb.service.d/limits.conf
      mode: "644"

- name: Ensure MariaDB is running
  ansible.builtin.systemd:
      name: mariadb
      enabled: true
      state: restarted
      daemon_reload: true

- name: Configure root user for socket authentication
  community.mysql.mysql_user:
      name: root
      plugin: unix_socket
      plugin_auth_string: ""
      host: localhost
      login_unix_socket: /var/run/mysqld/mysqld.sock
      state: present

- name: Remove anonymous MySQL users
  community.mysql.mysql_user:
      name: ""
      host_all: true
      login_unix_socket: /var/run/mysqld/mysqld.sock
      state: absent

- name: Remove MySQL test database
  community.mysql.mysql_db:
      name: test
      login_unix_socket: /var/run/mysqld/mysqld.sock
      state: absent

- name: Create databases for services
  community.mysql.mysql_db:
      name: freeflarum
      encoding: utf8mb4
      collation: utf8mb4_unicode_ci
      login_unix_socket: /var/run/mysqld/mysqld.sock
      state: present

- name: Create MySQL backup user
  community.mysql.mysql_user:
      name: backup
      plugin: unix_socket
      plugin_auth_string: ""
      priv: "*.*:SELECT,LOCK TABLES,SHOW VIEW,EVENT,TRIGGER"
      host: localhost
      login_unix_socket: /var/run/mysqld/mysqld.sock
      state: present

- name: Configure log rotation for MariaDB
  ansible.builtin.copy:
      src: files/etc/logrotate.d/mariadb
      dest: /etc/logrotate.d/mariadb
      mode: "644"
