---
- name: Install Python build dependencies
  ansible.builtin.apt:
      name:
          - build-essential
          - libssl-dev
          - zlib1g-dev
          - libbz2-dev
          - libreadline-dev
          - libsqlite3-dev
          - wget
          - curl
          - llvm
          - libncurses5-dev
          - libncursesw5-dev
          - xz-utils
          - libffi-dev
          - liblzma-dev
          - python3-openssl
          - git
      state: present

- name: Install Python {{ python_version }}
  ansible.builtin.apt:
      name:
          - "python{{ python_version }}"
          - "python{{ python_version }}-venv"
          - "python{{ python_version }}-dev"
      state: present

- name: Install pip for Python {{ python_version }}
  ansible.builtin.apt:
      name: python3-pip
      state: present
