---
- name: Install Python build dependencies
  ansible.builtin.apt:
      name:
          - libssl-dev
          - zlib1g-dev
          - libbz2-dev
          - libreadline-dev
          - libsqlite3-dev
          - llvm
          - libncurses5-dev
          - libncursesw5-dev
          - xz-utils
          - libffi-dev
          - liblzma-dev
      state: present
  tags: ["python", "mainsite"]

- name: Add Python repository
  ansible.builtin.apt_repository:
      repo: "ppa:deadsnakes/ppa"
      state: present
      update_cache: true
  tags: ["python", "mainsite"]

- name: Install Python {{ python_version }}
  ansible.builtin.apt:
      name:
          - "python{{ python_version }}"
          - "python{{ python_version }}-venv"
          - "python{{ python_version }}-dev"
          - python3-pip
          - python3-openssl
      state: present
  tags: ["python", "mainsite"]
