---
# https://github.com/FreeFlarum/freeflarum/blob/b1627f5e7ca1462272781e3b5a233d1226f89dfa/deploy/playbooks/main.yml#L41C1-L44C37
- name: Install Certbot
  ansible.builtin.apt:
      name:
          - certbot
          - python3-certbot-nginx
      state: present

- name: Create SSL directories
  ansible.builtin.file:
      path: "{{ item }}"
      state: directory
      mode: "755"
      owner: root
      group: root
  loop:
      - /etc/ssl/cloudflare
      - /etc/letsencrypt
      - /var/lib/letsencrypt
      - /var/log/letsencrypt

- name: Set up Certbot renewal cron job
  ansible.builtin.cron:
      name: "Renew Let's Encrypt certificates"
      minute: "0"
      hour: "2"
      job: "/usr/bin/certbot renew --quiet"
      user: root
      state: present

- name: Configure Certbot webroot
  ansible.builtin.copy:
      src: files/etc/letsencrypt/cli.ini
      dest: /etc/letsencrypt/cli.ini
      mode: "644"

- name: Configure SSL certificates
  ansible.builtin.copy:
      content: "{{ domains[item].ssl_certificate_pem }}"
      dest: "/etc/ssl/cloudflare/{{ item }}.pem"
      mode: "644"
      owner: root
      group: root
  loop: "{{ domains.keys() | list }}"
  when: domains is defined

- name: Configure SSL certificate keys
  ansible.builtin.copy:
      content: "{{ domains[item].ssl_certificate_key }}"
      dest: "/etc/ssl/cloudflare/{{ item }}.key"
      mode: "600"
      owner: root
      group: root
  loop: "{{ domains.keys() | list }}"
  when: domains is defined
