---
# FIXME

- name: Install mail packages
  ansible.builtin.apt:
      name:
          - postfix
          - postfix-pcre
          - opendkim
          - opendkim-tools
          - opendmarc
          - postgrey
          - spamassassin
          - spamc
      state: present

- name: Configure Postfix main.cf
  ansible.builtin.template:
      src: files/etc/postfix/main.cf
      dest: /etc/postfix/main.cf
      mode: "644"
      backup: true
  notify: restart postfix

- name: Configure Postfix master.cf
  ansible.builtin.template:
      src: files/etc/postfix/master.cf
      dest: /etc/postfix/master.cf
      mode: "644"
      backup: true
  notify: restart postfix

- name: Create virtual mailbox domains
  ansible.builtin.template:
      src: files/etc/postfix/virtual
      dest: /etc/postfix/virtual
      mode: "644"
  notify: postmap postfix_virtual

- name: Create sender access file
  ansible.builtin.template:
      src: files/etc/postfix/sender_access
      dest: /etc/postfix/sender_access
      mode: "644"
  notify: postmap postfix_sender_access

- name: Configure OpenDKIM
  ansible.builtin.template:
      src: files/etc/opendkim.conf
      dest: /etc/opendkim.conf
      mode: "644"
  notify: restart opendkim

- name: Create OpenDKIM keys directory
  ansible.builtin.file:
      path: /etc/opendkim/keys
      state: directory
      owner: opendkim
      group: opendkim
      mode: "700"

- name: Create OpenDKIM main domain key directory
  ansible.builtin.file:
      path: "/etc/opendkim/keys/{{ main_domain }}"
      state: directory
      owner: opendkim
      group: opendkim
      mode: "700"

- name: Copy OpenDKIM mail.private for main domain
  ansible.builtin.copy:
      dest: "/etc/opendkim/keys/{{ main_domain }}/mail.private"
      content: "{{ postfix.opendkim_domain_key }}"
      owner: opendkim
      group: opendkim
      mode: "644"

- name: Render OpenDKIM tables
  ansible.builtin.template:
      dest: "{{ item }}"
      src: "files{{ item }}"
      owner: opendkim
      group: opendkim
      mode: "644"
  loop:
      - /etc/opendkim/KeyTable
      - /etc/opendkim/SigningTable
      - /etc/opendkim/TrustedHosts
  notify: restart opendkim

- name: Configure SpamAssassin
  ansible.builtin.template:
      src: files/etc/spamassassin/local.cf
      dest: /etc/spamassassin/local.cf
      mode: "644"
  notify: restart spamassassin

- name: Configure Postgrey
  ansible.builtin.file:
      src: files/etc/default/postgrey
      dest: /etc/default/postgrey
      mode: "644"
  notify: restart postgrey

- name: Set up mail log rotation
  ansible.builtin.copy:
      src: files/etc/logrotate.d/postfix
      dest: /etc/logrotate.d/postfix
      mode: "644"

- name: Enable and start mail services
  ansible.builtin.systemd:
      name: "{{ item }}"
      enabled: true
      state: started
  loop:
      - postfix
      - opendkim
      - opendmarc
      - spamassassin
      - postgrey
