---
- name: Install mail packages
  ansible.builtin.apt:
      name:
          - postfix
          - postfix-pcre
          - opendkim
          - opendkim-tools
          - opendmarc
          - postgrey
          - spamc
      state: present
  tags: ["email", "mail", "postfix"]

- name: Install SpamAssassin
  ansible.builtin.apt:
      name: spamd
      state: present
  tags: ["email", "mail", "postfix"]

- name: Configure Postfix SSL certificate
  ansible.builtin.copy:
      content: "{{ postfix.mail_pem }}"
      dest: "/etc/ssl/cloudflare/{{ postfix.host }}.pem"
      mode: "644"
      owner: www-data
      group: www-data
  tags: ["email", "mail", "postfix", "ssl"]

- name: Configure Postfix SSL certificate key
  ansible.builtin.copy:
      content: "{{ postfix.mail_key }}"
      dest: "/etc/ssl/cloudflare/{{ postfix.host }}.key"
      mode: "600"
      owner: www-data
      group: www-data
  tags: ["email", "mail", "postfix", "ssl"]

- name: Configure Postfix main.cf
  ansible.builtin.template:
      src: files/etc/postfix/main.cf
      dest: /etc/postfix/main.cf
      mode: "644"
  tags: ["email", "mail", "postfix"]

- name: Configure Postfix master.cf
  ansible.builtin.template:
      src: files/etc/postfix/master.cf
      dest: /etc/postfix/master.cf
      mode: "644"
  tags: ["email", "mail", "postfix"]

- name: Create virtual mailbox domains
  ansible.builtin.template:
      src: files/etc/postfix/virtual
      dest: /etc/postfix/virtual
      mode: "644"
  tags: ["email", "mail", "postfix"]

- name: Generate virtual.db
  ansible.builtin.command:
      cmd: postmap /etc/postfix/virtual
      creates: /etc/postfix/virtual.db
  tags: ["email", "mail", "postfix"]

- name: Create sender access file
  ansible.builtin.template:
      src: files/etc/postfix/sender_access
      dest: /etc/postfix/sender_access
      mode: "644"
  tags: ["email", "mail", "postfix"]

- name: Generate sender_access.db
  ansible.builtin.command:
      cmd: postmap /etc/postfix/sender_access
      creates: /etc/postfix/sender_access.db
  tags: ["email", "mail", "postfix"]

- name: Add postfix user to milter groups
  ansible.builtin.user:
      name: postfix
      groups: "{{ milter_group }}"
      append: true
  loop:
      - opendkim
      - opendmarc
      - postgrey
  loop_control:
      loop_var: milter_group

- name: Ensure milter socket directories
  ansible.builtin.file:
      path: "/var/spool/postfix/{{ milter }}"
      owner: "{{ milter }}"
      group: "{{ milter }}"
      mode: "750"
      state: directory
  loop:
      - opendkim
      - opendmarc
      - postgrey
  loop_control:
      loop_var: milter

- name: Configure OpenDKIM and OpenDMARC
  ansible.builtin.template:
      src: "files/etc/{{ milter_conf }}.conf"
      dest: "/etc/{{ milter_conf }}.conf"
      mode: "644"
  loop:
      - opendkim
      - opendmarc
  loop_control:
      loop_var: milter_conf
  tags: ["email", "mail", "postfix"]

- name: Set OpenDKIM socket directory to Postfix chroot
  ansible.builtin.lineinfile:
      path: /etc/default/opendkim
      regexp: "^RUNDIR="
      line: "RUNDIR=/var/spool/postfix/opendkim"
  notify: restart opendkim
  tags: ["email", "mail", "postfix"]

- name: Set OpenDMARC socket directory to Postfix chroot
  ansible.builtin.lineinfile:
      path: /etc/default/opendmarc
      regexp: "^RUNDIR="
      line: "RUNDIR=/var/spool/postfix/opendmarc"
  notify: restart opendmarc
  tags: ["email", "mail", "postfix"]

- name: Create OpenDKIM keys directory
  ansible.builtin.file:
      path: /etc/opendkim/keys
      state: directory
      owner: opendkim
      group: opendkim
      mode: "700"
  tags: ["email", "mail", "postfix"]

- name: Create OpenDKIM main domain key directory
  ansible.builtin.file:
      path: "/etc/opendkim/keys/{{ main_domain }}"
      state: directory
      owner: opendkim
      group: opendkim
      mode: "700"
  tags: ["email", "mail", "postfix"]

- name: Copy OpenDKIM mail.private for main domain
  ansible.builtin.copy:
      dest: "/etc/opendkim/keys/{{ main_domain }}/mail.private"
      content: "{{ postfix.opendkim_domain_key }}"
      owner: opendkim
      group: opendkim
      mode: "600"
  tags: ["email", "mail", "postfix"]

- name: Copy OpenDKIM mail.txt for main domain
  ansible.builtin.copy:
      dest: "/etc/opendkim/keys/{{ main_domain }}/mail.txt"
      content: "{{ postfix.opendkim_dns_txt }}"
      owner: opendkim
      group: opendkim
      mode: "644"
  tags: ["email", "mail", "postfix"]

- name: Render OpenDKIM tables
  ansible.builtin.template:
      dest: "{{ dkim_table }}"
      src: "files{{ dkim_table }}"
      owner: opendkim
      group: opendkim
      mode: "644"
  loop:
      - /etc/opendkim/KeyTable
      - /etc/opendkim/SigningTable
      - /etc/opendkim/TrustedHosts
  loop_control:
      loop_var: dkim_table
  notify: restart opendkim
  tags: ["email", "mail", "postfix"]

- name: Configure SpamAssassin
  ansible.builtin.template:
      src: files/etc/spamassassin/local.cf
      dest: /etc/spamassassin/local.cf
      mode: "644"
  notify: restart spamassassin

- name: Configure Postgrey
  ansible.builtin.template:
      src: files/etc/default/postgrey
      dest: /etc/default/postgrey
      mode: "644"
  notify: restart postgrey

- name: Set up mail log rotation
  ansible.builtin.copy:
      src: files/etc/logrotate.d/postfix
      dest: /etc/logrotate.d/postfix
      mode: "644"

- name: Enable and start milter services
  ansible.builtin.systemd:
      name: "{{ milter_service }}"
      enabled: true
      state: started
  loop:
      - opendkim
      - opendmarc
      - postgrey
  loop_control:
      loop_var: milter_service

- name: Enable and start SpamAssassin
  ansible.builtin.systemd:
      name: spamd
      enabled: true
      state: started

- name: Enable and start postfix
  ansible.builtin.systemd:
      name: postfix
      enabled: true
      state: started
