---
- name: Create nocost system user
  ansible.builtin.user:
      name: nocost
      system: true
      shell: /usr/sbin/nologin
      create_home: false
  tags: ["nocost", "backend"]

- name: Add backend repo to git safe.directory to bypass perm checks
  ansible.builtin.command:
      cmd: "git config --global --add safe.directory {{ paths.backend_root }}"
  changed_when: false
  tags: ["nocost", "backend"] # noqa: command-instead-of-module

- name: Clone or update no-cost backend repository
  ansible.builtin.git:
      repo: "git@github.com:no-cost/backend.git"
      dest: "{{ paths.backend_root }}"
      version: "master"
      force: true
  tags: ["nocost", "backend"]

- name: Set backend repo to correct owner
  ansible.builtin.command:
      cmd: "chown -R nocost:nocost {{ paths.backend_root }}"
  changed_when: false
  tags: ["nocost", "backend"]

- name: Create virtual environment for main site
  ansible.builtin.command:
      cmd: "python3 -m venv {{ (paths.backend_root + '/.venv') | quote }}"
      creates: "{{ paths.backend_root }}/.venv/bin/python"
  tags: ["nocost", "backend"]

- name: Install Python packages for main site
  ansible.builtin.pip:
      requirements: "{{ paths.backend_root }}/requirements.txt"
      virtualenv: "{{ paths.backend_root }}/.venv"
      virtualenv_python: "python3"
  tags: ["nocost", "backend"]

- name: Ensure no-cost log directory
  ansible.builtin.file:
      path: /var/log/nocost
      state: directory
      owner: nocost
      group: nocost
      mode: "755"
  tags: ["nocost", "backend"]

- name: Ensure no-cost run directory
  ansible.builtin.file:
      path: /var/run/nocost
      state: directory
      owner: nocost
      group: nocost
      mode: "755"
  tags: ["nocost", "backend"]

- name: Create systemd service files for no-cost
  ansible.builtin.template:
      src: "files/etc/systemd/system/{{ nocost_service }}"
      dest: "/etc/systemd/system/{{ nocost_service }}"
      mode: "644"
  loop:
      - nocost.service
  loop_control:
      loop_var: nocost_service
  notify:
      - daemon reload
  tags: ["nocost", "backend"]

- name: Create environment configuration for no-cost backend
  ansible.builtin.template:
      src: "files/srv/backend/.env.template"
      dest: "{{ paths.backend_root }}/.env"
      owner: nocost
      group: nocost
      mode: "0640"
  tags: ["nocost", "backend"]

- name: Create database for nocost backend
  community.mysql.mysql_db:
      name: nocost
      encoding: utf8mb4
      collation: utf8mb4_unicode_ci
      login_unix_socket: /var/run/mysqld/mysqld.sock
      state: present
  tags: ["nocost", "backend"]

- name: Create database user for nocost backend
  community.mysql.mysql_user:
      name: nocost
      priv: "nocost.*:ALL"
      plugin: unix_socket
      plugin_auth_string: ""
      host: localhost
      login_unix_socket: /var/run/mysqld/mysqld.sock
      column_case_sensitive: true
      state: present
  tags: ["nocost", "backend"]

- name: Add Maxmind PPA repo
  ansible.builtin.apt_repository:
      repo: "ppa:maxmind/ppa"
      state: present
      update_cache: true
  tags: ["nocost", "geoip", "backend"]

- name: Install geoipupdate
  ansible.builtin.apt:
      package: geoipupdate
      state: present
  tags: ["nocost", "geoip", "backend"]

- name: Render GeoIP.conf
  ansible.builtin.template:
      src: files/etc/GeoIP.conf
      dest: /etc/GeoIP.conf
      mode: "644"
  tags: ["nocost", "geoip", "backend"]

- name: Install requirements
  ansible.builtin.pip:
      requirements: "{{ paths.backend_root }}/requirements.txt"
      virtualenv: "{{ paths.backend_root }}/.venv"
      virtualenv_python: "python3"
  tags: ["nocost", "test", "backend"]

- name: Run alembic migrations
  ansible.builtin.shell:
      cmd: "set -a && source .env && set +a && .venv/bin/alembic upgrade head"
      executable: "/bin/bash"
      chdir: "{{ paths.backend_root }}"
  become: true
  become_user: nocost
  changed_when: false
  tags: ["nocost", "backend"]

- name: Enable and start no-cost backend service
  ansible.builtin.systemd:
      name: nocost
      enabled: true
      state: restarted
  tags: ["nocost", "backend"]
