---
- name: Clone or update no-cost backend repository
  ansible.builtin.git:
      repo: "git@github.com:no-cost/backend.git"
      dest: "{{ paths.backend_root }}"
      version: "master"
      force: true
  tags: ["nocost"]

- name: Create required directories for nocost
  ansible.builtin.file:
      path: "{{ tenant_dir }}"
      state: directory
      owner: www-data
      group: www-data
      mode: "0755"
  loop:
      - "{{ paths.tenants.flarum_skeleton }}"
      - "{{ paths.tenants.wordpress_skeleton }}"
  loop_control:
      loop_var: tenant_dir
  tags: ["nocost"]

- name: Create virtual environment for main site
  ansible.builtin.command:
      cmd: "python3 -m venv {{ (paths.backend_root + '/.venv') | quote }}"
      creates: "{{ paths.backend_root }}/.venv/bin/python"
  tags: ["nocost"]

- name: Install Python packages for main site
  ansible.builtin.pip:
      requirements: "{{ paths.backend_root }}/requirements.txt"
      virtualenv: "{{ paths.backend_root }}/.venv"
      virtualenv_python: "python3"
  tags: ["nocost"]

- name: Ensure no-cost log directory
  ansible.builtin.file:
      path: /var/log/nocost/api/
      state: directory
      owner: www-data
      group: www-data
      mode: "755"
  tags: ["nocost"]

- name: Create systemd service files for no-cost
  ansible.builtin.template:
      src: "files/etc/systemd/system/{{ nocost_service }}"
      dest: "/etc/systemd/system/{{ nocost_service }}"
      mode: "644"
  loop:
      - nocost.service
      - nocost.socket
  loop_control:
      loop_var: nocost_service
  notify:
      - daemon reload
  tags: ["nocost"]

- name: Create environment configuration for no-cost backend
  ansible.builtin.copy:
      dest: "{{ paths.backend_root }}/.env"
      # TODO
      content: |
          # no-cost Backend Configuration
          DATABASE_HOST=localhost
          DATABASE_NAME=nocost
          DATABASE_USER=nocost

          # Paths
          TENANT_ROOT={{ paths.tenants.root }}
          FLARUM_SKELETON={{ paths.tenants.flarum_skeleton }}
          WORDPRESS_SKELETON={{ paths.tenants.wordpress_skeleton }}
          BACKUP_ROOT={{ paths.backup_root }}

          # Domains
          PRIMARY_DOMAINS=...
      owner: www-data
      group: www-data
      mode: "0640"
  tags: ["nocost"]

- name: Create database for nocost backend
  community.mysql.mysql_db:
      name: nocost
      encoding: utf8mb4
      collation: utf8mb4_unicode_ci
      login_unix_socket: /var/run/mysqld/mysqld.sock
      state: present
  tags: ["nocost"]

- name: Create database user for nocost backend
  community.mysql.mysql_user:
      name: nocost
      priv: "nocost.*:ALL"
      plugin: unix_socket
      plugin_auth_string: ""
      host: localhost
      login_unix_socket: /var/run/mysqld/mysqld.sock
      column_case_sensitive: true
      state: present
  tags: ["nocost"]

- name: Add Maxmind PPA repo
  ansible.builtin.apt_repository:
      repo: "ppa:maxmind/ppa"
      state: present
      update_cache: true
  tags: ["nocost", "geoip"]

- name: Install geoipupdate
  ansible.builtin.apt:
      package: geoipupdate
      state: present
  tags: ["nocost", "geoip"]

- name: Render GeoIP.conf
  ansible.builtin.template:
      src: files/etc/GeoIP.conf
      dest: /etc/GeoIP.conf
      mode: "644"
  tags: ["nocost", "geoip"]

- name: Start nocost service
  ansible.builtin.systemd:
      name: nocost.service
      enabled: true
      state: started
  tags: ["nocost"]
