---
- name: Install Composer 2
  ansible.builtin.get_url:
      url: https://getcomposer.org/download/latest-stable/composer.phar
      dest: /usr/local/bin/composer
      mode: "0755"
      force: true
  tags: ["skeleton", "chroot", "flarum", "mediawiki", "wordpress"]

- name: Ensure tenants root
  ansible.builtin.file:
      path: "{{ paths.tenants.root }}"
      state: directory
      owner: www-data
      group: www-data
      mode: "0755"
  tags: ["skeleton", "chroot", "flarum", "mediawiki", "wordpress"]

- name: Set up log rotation for tenant logs
  ansible.builtin.template:
      src: files/etc/logrotate.d/tenant
      dest: /etc/logrotate.d/tenant
      mode: "0644"
  tags: ["skeleton", "chroot", "flarum", "mediawiki", "wordpress"]

- name: Include all skeleton tasks
  ansible.builtin.include_tasks: "{{ item }}"
  with_fileglob:
      - ./skeletons/[!_]*.yml
  tags: [always]