---
- name: Install monitoring tools
  ansible.builtin.apt:
      name:
          - htop
          - iotop
          - iftop
          - sysstat
          - ncdu
          - vnstat
          - logwatch
          - monit
      state: present
      update_cache: true
  tags: ["monitoring"]

- name: Enable and start sysstat
  ansible.builtin.systemd:
      name: sysstat
      enabled: true
      state: started
  tags: ["monitoring"]

- name: Enable and start vnstat
  ansible.builtin.systemd:
      name: vnstat
      enabled: true
      state: started
  tags: ["monitoring"]

- name: Configure Monit
  ansible.builtin.template:
      src: files/etc/monit/monitrc
      dest: /etc/monit/monitrc
      owner: root
      group: root
      mode: "600"
  notify: restart monit
  tags: ["monitoring"]

- name: Create Monit service configurations
  ansible.builtin.template:
      src: "files/etc/monit/conf.d/{{ monit_service }}"
      dest: "/etc/monit/conf.d/{{ monit_service }}"
      owner: root
      group: root
      mode: "644"
  loop:
      - nginx
      - php-fpm
      - mariadb
      - postfix
      - disk
      - system
  loop_control:
      loop_var: monit_service
  notify: restart monit
  tags: ["monitoring"]

- name: Start and enable monit
  ansible.builtin.systemd:
      name: monit
      enabled: true
      state: started
  tags: ["monitoring"]

- name: Configure logwatch
  ansible.builtin.template:
      src: files/etc/logwatch/conf/logwatch.conf
      dest: /etc/logwatch/conf/logwatch.conf
      owner: root
      group: root
      mode: "644"
  tags: ["monitoring"]

- name: Disable daily logwatch cron
  ansible.builtin.file:
      path: /etc/cron.daily/00logwatch
      state: absent
  tags: ["monitoring"]

- name: Configure weekly logwatch cron
  ansible.builtin.template:
      src: files/etc/cron.d/logwatch
      dest: /etc/cron.d/logwatch
      owner: root
      group: root
      mode: "644"
  tags: ["monitoring"]
