---
- name: Run unit tests
  ansible.builtin.command:
      cmd: ".venv/bin/python -m pytest tests/unit/ -v"
      chdir: "{{ paths.backend_root }}"
  become: true
  become_user: nocost
  changed_when: false
  tags: ["tests"]

- name: Run integration tests
  ansible.builtin.command:
      cmd: ".venv/bin/python -m pytest tests/integration/ -v"
      chdir: "{{ paths.backend_root }}"
  become: true
  become_user: nocost
  changed_when: false
  timeout: 1800
  tags: ["tests"]
