# https://github.com/flarum/flarum/blob/cc4acfc61fb0f2cf0225de4e7a713a40bffaca69/.nginx.conf

server {
    listen unix:/run/tenants_flarum.sock;
    include /etc/nginx/snippets/tenant-common.conf;

    # prevent PHP execution in user uploads
    location ^~ /assets {
        # based on https://docs.flarum.org/install/#caddy
        try_files $uri =404;
        add_header Cache-Control "public, must-revalidate, proxy-revalidate";
        expires 12h;

        location ~ \.php$ {
            return 404;
        }
    }

    # php handler
    location ~ \.php$ {
        try_files $uri =404;
        include fastcgi_params;
        fastcgi_param REMOTE_ADDR $http_x_real_ip;
        fastcgi_param HTTPS on;
        fastcgi_index index.php;
        fastcgi_param DOCUMENT_ROOT /public;
        fastcgi_param SCRIPT_FILENAME /public/$fastcgi_script_name;
        fastcgi_pass unix:/run/php/php-fpm.$site_id.sock;
    }
    location @app {
        rewrite ^ /index.php?$query_string last;
    }
    location / {
        try_files $uri $uri/ @app;
    }
}
