# https://docs.flarum.org/install/#nginx

server {
    listen unix:/var/run/nginx/tenant_flarum.sock;
    include /etc/nginx/snippets/tenant-common.conf;

    # prevent PHP execution in user uploads
    location ^~ /assets {
        location ~ \.php$ {
            return 404;
        }
    }

    # php handler
    location ~ \.php$ {
        try_files $uri =404;
        include fastcgi_params;
        fastcgi_index index.php;
        fastcgi_param DOCUMENT_ROOT /public;
        fastcgi_param SCRIPT_FILENAME /public/$fastcgi_script_name;
        fastcgi_pass unix:/var/run/php/php-fpm.$site_id.sock;
    }
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }
}
