# https://www.mediawiki.org/wiki/Manual:Short_URL/Nginx
# https://shorturls.redwerks.org/

server {
    listen unix:/run/tenants_mediawiki.sock;
    include /etc/nginx/snippets/tenant-common.conf;

    # deny access to sensitive directories
    location ^~ /cache          { return 404; }
    location ^~ /languages      { return 404; }
    location ^~ /maintenance    { return 404; }
    location ^~ /serialized     { return 404; }
    location ^~ /sql            { return 404; }
    location ^~ /vendor         { return 404; }
    location ^~ /images/deleted { return 404; }

    location /images {
        # prevent PHP execution in images
        add_header X-Content-Type-Options "nosniff";
        location ~ \.php$ {
            return 404;
        }

        # thumbnail handler
        location ~ ^/images/thumb/(archive/)?[0-9a-f]/[0-9a-f][0-9a-f]/([^/]+)/([0-9]+)px-.*$ {
            try_files $uri $uri/ @thumb;
        }
    }
    location @thumb {
        rewrite ^/images/thumb/[0-9a-f]/[0-9a-f][0-9a-f]/([^/]+)/([0-9]+)px-.*$ /thumb.php?f=$1&width=$2 last;
        rewrite ^/images/thumb/archive/[0-9a-f]/[0-9a-f][0-9a-f]/([^/]+)/([0-9]+)px-.*$ /thumb.php?f=$1&width=$2&archived=1 last;
    }

    # static assets
    location ~ ^/resources/(assets|lib|src) {
        try_files $uri =404;
        add_header Cache-Control "public";
        expires 7d;
    }
    location ~ ^/(skins|extensions)/.+\.(css|js|gif|jpg|jpeg|png|svg|wasm|ttf|woff|woff2)$ {
        try_files $uri =404;
        add_header Cache-Control "public";
        expires 7d;
    }
    location ~ ^/(COPYING|CREDITS)$ {
        default_type text/plain;
    }

    # php handlers
    location /rest.php/ {
        try_files $uri $uri/ /rest.php?$query_string;
    }
    location ~ \.php$ {
        try_files $uri =404;
        include fastcgi_params;
        fastcgi_param REMOTE_ADDR $http_x_real_ip;
        fastcgi_param HTTPS on;
        fastcgi_index index.php;
        fastcgi_param DOCUMENT_ROOT /public;
        fastcgi_param SCRIPT_FILENAME /public/$fastcgi_script_name;
        fastcgi_pass unix:/run/php/php-fpm.$site_id.sock;
    }

    # /Main_Page -> index.php?title=Main_Page
    location / {
        try_files $uri $uri/ @app;
    }
    location @app {
        rewrite ^/(.+)$ /index.php?title=$1&$args last;
    }
}
