# https://developer.wordpress.org/advanced-administration/server/web-server/nginx/

server {
    listen unix:/run/nginx/tenants_wordpress.sock;
    include /etc/nginx/snippets/tenant-common.conf;

    # deny access to sensitive files
    location = /wp-config.php {
        return 404;
    }
    location = /xmlrpc.php {
        return 404;
    }
    location ~ ^/wp-includes/(?!js/tinymce/).*\.php$ {
        return 404;
    }
    location ~ ^/wp-content/uploads/.*\.php$ {
        return 404;
    }

    # php handler
    location ~ \.php$ {
        try_files $uri =404;
        include fastcgi_params;
        fastcgi_index index.php;
        fastcgi_param REMOTE_ADDR $http_x_real_ip;
        fastcgi_param HTTPS on;
        fastcgi_param DOCUMENT_ROOT /public;
        fastcgi_param SCRIPT_FILENAME /public/$fastcgi_script_name;
        fastcgi_pass unix:/run/php/php-fpm.$site_id.sock;
    }
    location / {
        try_files $uri $uri/ /index.php?$args;
    }
}
