server {
    listen 80;
    listen [::]:80;
    server_name {% for domain in domains.keys() %}*.{{ domain }}{% if not loop.last %} {% endif %}{% endfor %};

    return 301 https://$host$request_uri;
}

map $ssl_server_name $cert_name {
{% for domain in domains.keys() %}
    ~^(.+\.)?{{ domain | regex_escape }}$ {{ domain }};
{% endfor %}
    default {{ domains.keys() | first }};
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name {% for domain in domains.keys() %}*.{{ domain }}{% if not loop.last %} {% endif %}{% endfor %};

    ssl_certificate /etc/ssl/cloudflare/$cert_name.pem;
    ssl_certificate_key /etc/ssl/cloudflare/$cert_name.key;
    include /etc/nginx/snippets/ssl-params.conf;

    # reject unknown hosts (not in maps/sites.conf)
    if ($site_id = "") {
        return 404;
    }

    root {{ paths.tenants.root }}/$site_id/public;
    index index.php index.html;

    include /etc/nginx/snippets/security-headers.conf;
    access_log {{ paths.tenants.root }}/$site_id/logs/access.log json_access;

    # deny dotfiles (except .well-known for ACME)
    location ~ /\.(?!well-known) {
        return 404;
    }

    # service rules
    location / {
        try_files $uri $uri/ @$service_type;
    }
    include /etc/nginx/service-rules/*.conf;
    location ~ \.php$ {
        try_files $uri =404;
        include fastcgi_params;
        fastcgi_index index.php;
        fastcgi_param DOCUMENT_ROOT /public;
        fastcgi_param SCRIPT_FILENAME /public/$fastcgi_script_name;
        fastcgi_pass unix:/var/run/php/php-fpm.$site_id.sock;
    }

    # needs separate definition, otherwise it's superceded by the expiration rules below
    location = /sitemap.xml {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # the following directives are based on best practices from H5BP Nginx Server Configs
    # "access_log off" > disables access log for static assets
    # https://github.com/h5bp/server-configs-nginx

    location ~* \.(?:manifest|appcache|html?|xml|json)$ {
        add_header Cache-Control "max-age=0";
    }

    location ~* \.(?:rss|atom)$ {
        add_header Cache-Control "max-age=3600";
    }

    location ~* \.(?:jpg|jpeg|gif|png|ico|cur|gz|svg|mp4|ogg|ogv|webm|htc)$ {
        add_header Cache-Control "max-age=2592000";
        access_log off;
    }

    location ~* \.(?:css|js)$ {
        add_header Cache-Control "max-age=31536000";
        access_log off;
    }

    location ~* \.(?:ttf|ttc|otf|eot|woff|woff2)$ {
        add_header Cache-Control "max-age=2592000";
        access_log off;
    }
}
