# redirect to main domain
server {
    listen 80;
    listen [::]:80;
    server_name {% for domain in domains.keys() %}{{ domain }}{% if not loop.last %} {% endif %}{% endfor %};

    return 301 https://{{ main_domain }}$request_uri;
}
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name {% for domain in domains.keys() %}{{ domain }}{% if not loop.last %} {% endif %}{% endfor %};

    ssl_certificate $ssl_cert_dir/fullchain.pem;
    ssl_certificate_key $ssl_cert_dir/privkey.pem;
    include /etc/nginx/snippets/ssl-params.conf;
    include /etc/nginx/snippets/security-headers.conf;

    return 301 https://{{ main_domain }}$request_uri;
}

# main domain
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name {{ main_domain }};

    ssl_certificate /etc/ssl/wildcard/{{ main_domain }}/fullchain.pem;
    ssl_certificate_key /etc/ssl/wildcard/{{ main_domain }}/privkey.pem;
    include /etc/nginx/snippets/ssl-params.conf;
    include /etc/nginx/snippets/security-headers.conf;

    access_log /var/log/nginx/{{ main_domain }}-access.log json_access;

    location ~ ^/api {
        limit_req zone=api burst=10 nodelay;
        proxy_pass http://unix:/var/run/uvicorn.sock;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $server_name;
        proxy_read_timeout 86400;
    }

    location / {
        root {{ paths.frontend_root }}/dist;
        try_files $uri $uri/ /index.html;
    }
}
