- name: Cron - Backup all forums
  ansible.builtin.cron:
    name: backup
    minute: "0"
    hour: "23"
    user: root
    job: "flock -n ~/.freeflarum-backup.lock /data/freeflarum/bin/backup 2>&1 | ts -i > /var/log/freeflarum/backup.log"
    cron_file: freeflarum


- name: Cron - Check if `skeleton` forum is timing out
  ansible.builtin.cron:
    name: check-timeout
    minute: "*/5"
    user: root
    job: "bash /data/freeflarum/freeflarum/backend/commands/check_timeout.sh 2>&1 | tee -a /var/log/freeflarum/timeouts.log"
    cron_file: freeflarum


- name: Cron - Cleanup forums
  ansible.builtin.cron:
    name: cleanup
    minute: "0"
    hour: "2"
    day: "1"
    month: "*/6"
    user: root
    job: "PYTHONPATH=/data/freeflarum /data/freeflarum/env/bin/python /data/freeflarum/freeflarum/backend/commands/cleanup.py > /var/log/freeflarum/cleanup.log"
    cron_file: freeflarum


- name: Cron - Kill lesscachce older than 1 day
  ansible.builtin.cron:
    name: kill-lesscachce
    minute: "0"
    hour: "20"
    user: root
    job: "ionice -c3 find /data/host/ -path '*/storage/less/*.lesscache' -type f -mtime +1 -delete"
    cron_file: freeflarum


- name: Cron - Update GeoIP every week
  ansible.builtin.cron:
    name: update-geoip
    minute: "0"
    hour: "5"
    weekday: "7"
    user: root
    job: "/usr/bin/geoipupdate -d /etc/geoip"
    cron_file: freeflarum
