- name: Setup Composer v2
  ansible.builtin.get_url:
    url: https://getcomposer.org/download/latest-stable/composer.phar
    dest: /usr/bin/composer
    owner: root
    mode: "0755"


- name: Create Flarum hosts & backup directories
  ansible.builtin.file:
    state: directory
    path: '{{ item }}'
    mode: "0755"
    owner: www-data
    group: www-data
  loop:
    - '{{ flarum_hosts_root }}'
    - '{{ backups_root }}/attic'
    - '{{ backups_root }}/host'
    - '{{ backups_root }}/system'


- name: Clone skeleton repository
  ansible.builtin.git:
    repo: git@github.com:FreeFlarum/flarum-multitenant.git
    dest: '{{ skeleton_root }}'
    version: master
    force: true


- name: Fix permissions of skeleton directory
  ansible.builtin.file:
    path: '{{ skeleton_root }}'
    state: directory
    mode: "0755"
    recurse: true
    owner: www-data
    group: www-data


- name: Install Flarum using Composer
  ansible.builtin.shell:
    cmd: yes | composer install --no-dev --prefer-dist --no-progress --no-suggest --no-interaction --optimize-autoloader
    chdir: '{{ skeleton_root }}/'


- name: Install Flarum database
  community.mysql.mysql_db:
    name: flarum_skeleton
    state: present
    login_unix_socket: /run/mysqld/mysqld.sock


- name: Create skeleton database user
  community.mysql.mysql_user:
    name: flarum_skeleton
    password: '{{ skeleton_database_password }}'
    priv: flarum_skeleton.*:ALL
    state: present
    login_unix_socket: /run/mysqld/mysqld.sock


- name: Install PHP-FPM config
  ansible.builtin.template:
    src: '{{ playbook_dir }}/../../freeflarum/backend/templates/fpm_pool.conf'
    dest: /etc/php/fpm/pool.d/{{ forum.tag }}.conf
    owner: root
    group: root
    mode: "0644"
  loop:
    - tag: skeleton
      paths:
        ROOT: /data/host/skeleton
        PUBLIC_ROOT: /data/host/skeleton/public
  loop_control:
    loop_var: forum


- name: Generate skeleton database password
  ansible.builtin.set_fact:
    skeleton_database_password: "{{ lookup('password', '/dev/null chars=ascii_lowercase,digits length=8') }}"

- name: Create `config.php`
  ansible.builtin.template:
    src: '{{ playbook_dir }}/../../freeflarum/backend/templates/config.php'
    dest: '{{ skeleton_root }}/config.php'
    owner: root
    group: root
    mode: "0644"
  vars:
    forum:
      tag: skeleton
      flarum_database_name: flarum_skeleton
      canonical_url: https://skeleton.{{ main_domain }}
    database_password: '{{ skeleton_database_password }}'


- name: Symlink skeleton forum
  ansible.builtin.file:
    src: '{{ skeleton_root }}/'
    dest: /var/skeleton
    state: link


- name: Add `skeleton` forum to FreeFlarum database
  community.mysql.mysql_query:
    query: 'INSERT IGNORE INTO freeflarum.forums (`tag`, `email`, `parent_domain`, `status`, `donated_amount`, `protected`) VALUES ("skeleton", "info@{{ main_domain }}", "{{ main_domain }}", "online", 0, 1);'
    login_unix_socket: /run/mysqld/mysqld.sock


- name: Import Flarum minimal database to skeleton
  community.mysql.mysql_db:
    name: flarum_skeleton
    state: import
    login_unix_socket: /run/mysqld/mysqld.sock
    target: ../../freeflarum/backend/templates/flarum.sql


- name: Disable sign up for `skeleton`, to prevent spam accounts
  community.mysql.mysql_query:
    query: "UPDATE flarum_skeleton.settings SET `value` = 0 WHERE `key` = 'allow_sign_up';"
    login_unix_socket: /run/mysqld/mysqld.sock


- name: Clear cache and migrate database
  ansible.builtin.shell:
    cmd: php flarum cache:clear && php flarum migrate
    chdir: '{{ skeleton_root }}/'
  register: output
  changed_when: output.rc != 0
  become: true
  become_user: www-data


- name: Restart PHP-FPM
  ansible.builtin.service:
    name: php{{ php_version }}-fpm
    state: restarted


- name: Restart MariaDB
  ansible.builtin.service:
    name: mariadb
    state: restarted
