- name: Add Maxmind APT repository
  ansible.builtin.apt_repository:
    repo: ppa:maxmind/ppa
    state: present


- name: Create `/etc/geoip`
  ansible.builtin.file:
    state: directory
    path: '/etc/geoip'
    mode: "0775"
    owner: root
    group: root


- name: Install geoipupdate
  ansible.builtin.apt:
    name: geoipupdate
    state: present
    update_cache: true


- name: Install GeoIP.conf
  ansible.builtin.template:
    src: files/etc/GeoIP.conf
    dest: /etc/GeoIP.conf
    owner: root
    group: root
    mode: "0644"


- name: Run `geoipupdate`
  ansible.builtin.command:
    cmd: /usr/bin/geoipupdate -v
  register: geoipupdate_output
  changed_when: geoipupdate_output.rc != 0
