- name: Add PPA for PHP
  ansible.builtin.apt_repository:
    repo: ppa:ondrej/php
    state: present


- name: Install PHP packages
  ansible.builtin.apt:
    state: present
    update_cache: true
    pkg:
      - php{{ php_version }}-fpm
      - php{{ php_version }}-zip
      - php{{ php_version }}-curl
      - php{{ php_version }}-gd
      - php{{ php_version }}-mbstring
      - php{{ php_version }}-xml
      - php{{ php_version }}-mysql
      - php{{ php_version }}-gmp
      - php{{ php_version }}-intl


- name: Create PHP-FPM override directory
  ansible.builtin.file:
    path: /etc/systemd/system/php{{ php_version }}-fpm.service.d
    state: directory
    mode: "0755"


- name: Add PHP-FPM service override
  ansible.builtin.copy:
    src: files/etc/systemd/php-fpm-override.conf
    dest: /etc/systemd/system/php{{ php_version }}-fpm.service.d/override.conf
    mode: "0644"
  notify: restart-fpm


- name: Install PHP-FPM config files
  ansible.builtin.template:
    src: files/etc/php/fpm/{{ item }}
    dest: /etc/php/{{ php_version }}/fpm/{{ item }}
    mode: "0644"
  loop:
    - pool.d/www.conf
    - php-fpm.conf
    - php.ini
    - generic_pool.conf
  notify: restart-fpm


- name: Symlink FPM config directory
  ansible.builtin.file:
    src: /etc/php/{{ php_version }}/fpm
    dest: /etc/php/fpm
    state: link
    force: true


- name: Ensure that PHP-FPM service is started
  ansible.builtin.service:
    name: php{{ php_version }}-fpm
    enabled: true
    state: started


# print a note to remove old php version
- name: Print note to remove old PHP version
  ansible.builtin.debug:
    msg: |
      In case you are upgrading to a new PHP-FPM version via this script,
      you may want to purge the old PHP version too:

      `sudo apt remove php<old_version>* --purge`

      FreeFlarum supports only 1 PHP version (usually the latest one), so the other ones
      are redundant and should be purged to save disk space and server resources.

      Verify:
        1. If the packages shown are the ones that need to be removed;
        2. If old config files need to be moved to the new version (Ansible does not overwrite the existing ones,
           so adjust them in the deploy scripts too if needed);

      If the above requirements are not met, then either adjust the command or at least stop the old PHP-FPM service,
      to keep configs but to also free up system resources (the new version should be used instead)
