- name: Install Postfix and Postgrey
  ansible.builtin.apt:
    pkg:
      - postfix
      - postgrey
    state: present
    update_cache: true


- name: Install Postfix config
  ansible.builtin.template:
    src: files/etc/postfix/main.cf
    dest: /etc/postfix/main.cf
    mode: "0644"


- name: Install Postgrey default file
  ansible.builtin.template:
    src: files/etc/default/postgrey
    dest: /etc/default/postgrey
    mode: "0644"


- name: Install recipient canonical map
  ansible.builtin.template:
    src: files/etc/postfix/recipient_canonical
    dest: /etc/postfix/recipient_canonical
    mode: "0644"


- name: Update recipient canonical map
  ansible.builtin.command:
    cmd: postmap /etc/postfix/recipient_canonical
  register: output
  changed_when: output.rc != 0
  notify: reload-postfix


- name: Ensure that Postfix and Postgrey are started
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: true
    state: started
  loop:
    - postfix
    - postgrey
