- name: Install pip3 and venv
  ansible.builtin.apt:
    pkg:
      - python3-pip
      - python{{ python_version  }}-venv
      - gcc
      - python{{ python_version }}-dev
    state: present
    update_cache: true


- name: Install PyMySQL globally for Ansible MySQL support
  ansible.builtin.pip:
    name: pymysql


- name: Install FreeFlarum requirements in virtual environment
  ansible.builtin.pip:
    requirements: '{{ playbook_dir }}/../../requirements.txt'
    virtualenv: '{{ playbook_dir }}/../../.venv'
    virtualenv_command: "python{{ python_version }} -m venv"


- name: Symlink latest Python to `/usr/bin/python`
  ansible.builtin.file:
    state: link
    src: '/usr/bin/python{{ python_version }}'
    dest: /usr/bin/python


- name: Run Python script to create database tables
  ansible.builtin.command:
    cmd: ".venv/bin/python{{ python_version }} -m freeflarum.backend.database.engine"
    chdir: "{{ playbook_dir }}/../../"
