---
- name: Render config.json template with tenant information
  ansible.builtin.template:
      src: files/srv/skeleton/flarum/etc/config.json
      dest: "{{ paths.tenants.root }}/{{ tenant_tag }}/etc/config.json"
      owner: "tenant_{{ tenant_tag }}"
      group: "tenant_{{ tenant_tag }}"
      mode: "644"
