---
- name: Create symbolic link for Flarum logs
  ansible.builtin.file:
    state: link
    src: "app/storage/logs"
    dest: "logs/flarum"
    force: true
    owner: "tenant_{{ tenant_id }}"
    group: "tenant_{{ tenant_id }}"
    mode: "644"
  args:
    chdir: "{{ paths.tenants.root }}/{{ tenant_id }}"
