---
# app root in /app/
- name: Copy skeleton structure and mount vendor
  ansible.builtin.include_tasks: ./helpers/copy_structure.yml
  vars:
      mount_paths: ["app/vendor"]
      exclude_paths: ["etc/config.json"]
      service_type: "flarum"
  tags: [always]

- name: Render config.json template with tenant information
  ansible.builtin.template:
      src: files/srv/skeleton/flarum/etc/config.json
      dest: "{{ paths.tenants.root }}/{{ tenant_tag }}/etc/config.json"
      owner: "tenant_{{ tenant_tag }}"
      group: "tenant_{{ tenant_tag }}"
      mode: "640"
  tags: ["skeleton", "flarum"]
