- name: Check if tenant already exists
  ansible.builtin.stat:
      path: "{{ paths.tenants.root }}/{{ tenant_tag }}"
  register: tenant_exists

- name: Fail if tenant already exists
  ansible.builtin.fail:
      msg: "Tenant directory `{{ paths.tenants.root }}/{{ tenant_tag }}` already exists!"
  when: not force and tenant_exists.stat.exists

- name: Create tenant Linux user
  ansible.builtin.user:
      name: "tenant_{{ tenant_tag }}"
      shell: /sbin/nologin
      create_home: false

- name: Copy skeleton directory structure
  ansible.posix.synchronize:
      src: "{{ paths.tenants.skeleton_root }}/{{ service_type }}/"
      dest: "{{ paths.tenants.root }}/{{ tenant_tag }}/"
      rsync_opts:
          - "--exclude=/etc/config.json"
          - "--exclude=/app/vendor"
      recursive: true
      links: true
  delegate_to: "{{ inventory_hostname }}"

- name: Set ownership for tenant dirs
  ansible.builtin.shell:
      # must chown /app only, or else it will set perms on hardlinked libs
      cmd: |
          find {{ (paths.tenants.root + "/" + tenant_tag + "/app") | quote }} \
          -path {{ (paths.tenants.root + "/" + tenant_tag + "/app/vendor") | quote }} -prune -o \
          -exec chown {{ ("tenant_" + tenant_tag + ":tenant_" + tenant_tag) | quote }} {} +
      executable: /bin/bash
  changed_when: true

- name: Set ownership of root tenant dirs
  ansible.builtin.file:
      path: "{{ paths.tenants.root }}/{{ tenant_tag }}/{{ root_tenant_dir }}"
      owner: "tenant_{{ tenant_tag }}"
      group: "tenant_{{ tenant_tag }}"
      mode: "775"
  loop:
      - "tmp"
      - "session"
  loop_control:
      loop_var: root_tenant_dir

- name: Create tenant database
  community.mysql.mysql_db:
      name: "tenant_{{ tenant_tag }}"
      encoding: utf8mb4
      collation: utf8mb4_unicode_ci
      login_unix_socket: /var/run/mysqld/mysqld.sock
      state: present

- name: Generate database password
  ansible.builtin.set_fact:
      db_password: "{{ tenant_db_password | default(lookup('password', '/dev/null chars=ascii_letters,digits length=20')) }}"

- name: Create database user for tenant
  community.mysql.mysql_user:
      name: "tenant_{{ tenant_tag }}"
      password: "{{ db_password }}"
      priv: "tenant_{{ tenant_tag }}.*:ALL"
      host: 127.0.0.1
      login_unix_socket: /var/run/mysqld/mysqld.sock
      state: present

- name: Check database template availability
  ansible.builtin.stat:
      path: "files/srv/skeleton/{{ service_type }}/database.sql"
  delegate_to: localhost
  register: database_template

- name: Render db template
  ansible.builtin.template:
      src: "files/srv/skeleton/{{ service_type }}/database.sql"
      dest: "/tmp/tenant_{{ tenant_tag }}_database.sql"
      mode: "600"
  when: database_template.stat.exists

- name: Import rendered db template
  community.mysql.mysql_db:
      name: "tenant_{{ tenant_tag }}"
      state: import
      target: "/tmp/tenant_{{ tenant_tag }}_database.sql"
      login_unix_socket: /var/run/mysqld/mysqld.sock
  when: database_template.stat.exists

- name: Cleanup rendered temp db template
  ansible.builtin.file:
      path: "/tmp/tenant_{{ tenant_tag }}_database.sql"
      state: absent
  when: database_template.stat.exists

- name: Create PHP-FPM pool for tenant
  ansible.builtin.template:
      src: files/etc/php/fpm/pool-template.conf
      dest: /etc/php/fpm/pool.d/{{ tenant_tag }}.conf
      mode: "644"

- name: Check if vendor directory exists
  ansible.builtin.stat:
      path: "{{ paths.tenants.root }}/{{ tenant_tag }}/app/vendor"
  register: vendor_dir

- name: Create mount point for vendor directory if it doesn't exist
  ansible.builtin.file:
      path: "{{ paths.tenants.root }}/{{ tenant_tag }}/app/vendor"
      state: directory
      owner: "tenant_{{ tenant_tag }}"
      group: "tenant_{{ tenant_tag }}"
      mode: "755"
  when: not vendor_dir.stat.exists

- name: Mount vendor directory as read-only bind mount
  ansible.posix.mount:
      src: "{{ paths.tenants.skeleton_root }}/{{ service_type }}/app/vendor"
      path: "{{ paths.tenants.root }}/{{ tenant_tag }}/app/vendor"
      opts: ro,bind
      state: mounted
      fstype: none

- name: "Deploy {{ service_type }}"
  ansible.builtin.include_tasks: "./{{ service_type }}.yml"

# TODO: fix mail sending
- name: Send welcome email
  community.general.mail:
      to: "{{ tenant_admin_email }}"
      subject: "Welcome to FreeFlarum!"
      body: |
          Your `{{ service_type }}` instance has been provisioned successfully!

          Domain: {{ tenant_tag }}.freeflarum.com
          Service: {{ service_type | capitalize }}

          If you have any questions, please let us know by replying to this e-mail.
      from: "noreply@{{ main_domain }}"
  failed_when: false

- name: Reload services
  ansible.builtin.systemd:
      name: "{{ web_service }}"
      state: reloaded
  loop:
      - "php{{ php_version }}-fpm"
      - nginx
  loop_control:
      loop_var: web_service
