---
# app root in /app/public/
- name: Copy skeleton structure and mount MediaWiki core directories
  ansible.builtin.include_tasks: ./helpers/copy_structure.yml
  vars:
      mount_paths:
          - "app/public/extensions"
          - "app/public/includes"
          - "app/public/languages"
          - "app/public/skins"
          - "app/public/sql" # for db migrations
          - "app/public/vendor"
      exclude_paths:
          - "app/public/tests"
          - "app/public/README.md"
      service_type: "mediawiki"
  tags: ["skeleton", "mediawiki"]

- name: Run MediaWiki installation script
  ansible.builtin.shell:
      cmd: |
          php maintenance/run.php install \
          --dbname="tenant_mediawiki_skeleton" \
          --dbserver="127.0.0.1" \
          --dbuser="tenant_mediawiki_skeleton" \
          --dbpass={{ skeletons.mediawiki_db_password | quote }} \
          --server={{ ('https://mediawiki_skeleton.' + main_domain) | quote }} \
          --scriptpath="" \
          --lang="en" \
          --pass={{ skeletons.mediawiki_admin_password | quote }} {{ (tenant_tag | replace("_", " ") | title) | quote }} "Admin"
      chdir: "{{ paths.tenants.root }}/{{ tenant_tag }}/app/public"
  changed_when: true
  tags: ["skeleton", "mediawiki"]

- name: Set MediaWiki article path
  ansible.builtin.blockinfile:
      path: "{{ paths.tenants.root }}/{{ tenant_tag }}/app/public/LocalSettings.php"
      block: |
          $wgArticlePath = "/$1";
          $wgUsePathInfo = true;
          $wgScriptExtension = ".php";
      marker: "# {mark} NC - ARTICLE PATH TWEAKS"
      insertafter: EOF
  tags: ["skeleton", "mediawiki"]

- name: Enable file uploads in MediaWiki
  ansible.builtin.lineinfile:
      path: "{{ paths.tenants.root }}/{{ tenant_tag }}/app/public/LocalSettings.php"
      regexp: '^\$wgEnableUploads = false;'
      line: '$wgEnableUploads = true;'
  tags: ["skeleton", "mediawiki"]
