---
- name: Check if tenant already exists
  ansible.builtin.stat:
      path: "{{ paths.tenants.root }}/{{ tenant_tag }}"
  register: tenant_exists
  tags: [always]

- name: Fail if tenant already exists
  ansible.builtin.fail:
      msg: "Tenant directory `{{ paths.tenants.root }}/{{ tenant_tag }}` already exists!"
  when: not force and tenant_exists.stat.exists
  tags: [always]

- name: Create tenant Linux user
  ansible.builtin.user:
      name: "tenant_{{ tenant_tag }}"
      shell: /sbin/nologin
      create_home: false
  tags: [always]

- name: Create tenant database
  community.mysql.mysql_db:
      name: "tenant_{{ tenant_tag }}"
      encoding: utf8mb4
      collation: utf8mb4_unicode_ci
      login_unix_socket: /var/run/mysqld/mysqld.sock
      state: present
  tags: [always]

- name: Create database user for tenant
  community.mysql.mysql_user:
      name: "tenant_{{ tenant_tag }}"
      password: "{{ tenant_db_password }}"
      priv: "tenant_{{ tenant_tag }}.*:ALL"
      host: 127.0.0.1
      login_unix_socket: /var/run/mysqld/mysqld.sock
      column_case_sensitive: true
      state: present
  tags: [always]

- name: Check database template availability
  ansible.builtin.stat:
      path: "files/srv/skeleton/{{ service_type }}/database.sql"
  delegate_to: localhost
  register: database_template
  tags: [always]

- name: Render db template
  ansible.builtin.template:
      src: "files/srv/skeleton/{{ service_type }}/database.sql"
      dest: "/tmp/tenant_{{ tenant_tag }}_database.sql"
      mode: "600"
  when: database_template.stat.exists
  tags: [always]

- name: Import rendered db template
  community.mysql.mysql_db:
      name: "tenant_{{ tenant_tag }}"
      state: import
      target: "/tmp/tenant_{{ tenant_tag }}_database.sql"
      login_unix_socket: /var/run/mysqld/mysqld.sock
  when: database_template.stat.exists
  tags: [always]

- name: Cleanup rendered temp db template
  ansible.builtin.file:
      path: "/tmp/tenant_{{ tenant_tag }}_database.sql"
      state: absent
  when: database_template.stat.exists
  tags: [always]

- name: Create PHP-FPM pool for tenant
  ansible.builtin.template:
      src: files/etc/php/fpm/pool-template.conf
      dest: /etc/php/fpm/pool.d/{{ tenant_tag }}.conf
      mode: "644"
  tags: [always]

- name: "Deploy {{ service_type }}"
  ansible.builtin.include_tasks: "./{{ service_type }}.yml"
  tags: [always]

# TODO: fix mail sending
- name: Send welcome email
  community.general.mail:
      to: "{{ tenant_admin_email | default('info@freeflarum.dev') }}"
      subject: "Welcome to FreeFlarum!"
      body: |
          Your `{{ service_type }}` instance has been provisioned successfully!

          Domain: {{ tenant_tag }}.freeflarum.com
          Service: {{ service_type | capitalize }}

          If you have any questions, please let us know by replying to this e-mail.
      from: "noreply@{{ main_domain }}"
  failed_when: false
  tags: [always]

- name: Reload services
  ansible.builtin.systemd:
      name: "{{ web_service }}"
      state: reloaded
  loop:
      - "php{{ php_version }}-fpm"
      - nginx
  loop_control:
      loop_var: web_service
  tags: [always]
