[www]

user = www-data
group = www-data

listen = /run/php/php-fpm.sock
listen.owner = www-data
listen.group = www-data

pm = ondemand
pm.max_children = 2
pm.process_idle_timeout = 10s

php_admin_value[memory_limit] = 512M
