# https://docs.flarum.org/install/#nginx

location @flarum {
    # caching & friends already in dynamic.conf and snippets
    # prevent PHP execution in assets (user uploads)
    location /assets {
        location ~ \.php$ {
            return 404;
        }
    }

    # flarum
    try_files $uri $uri/ /index.php?$query_string;
}
