# https://developer.wordpress.org/advanced-administration/server/web-server/nginx/

location @wordpress {
    location = /wp-config.php {
        return 404;
    }

    # deny xmlrpc.php (common attack vector for malware)
    location = /xmlrpc.php {
        return 404;
    }

    # deny PHP in wp-includes (except tinymce)
    location ~ ^/wp-includes/(?!js/tinymce/).*\.php$ {
        return 404;
    }

    # deny PHP execution in uploads
    location ~ ^/wp-content/uploads/.*\.php$ {
        return 404;
    }

    # WordPress pretty permalinks
    try_files $uri $uri/ /index.php?$args;
}
