# get site_id from header
set $site_id $http_x_tenant_id;

root {{ paths.tenants.root }}/$site_id/public;
index index.php index.html;

include /etc/nginx/snippets/security-headers.conf;
access_log {{ paths.tenants.root }}/$site_id/logs/access.log json_access;

# deny hidden files (except .well-known)
location ~ /\.(?!well-known) {
    return 404;
}

# static assets
# github.com/h5bp/server-configs-nginx
location = /sitemap.xml {
    try_files $uri $uri/ /index.php?$query_string;
}
location ~* \.(?:manifest|appcache|html?|xml|json)$ {
    add_header Cache-Control "max-age=0";
}
location ~* \.(?:rss|atom)$ {
    add_header Cache-Control "max-age=3600";
}
location ~* \.(?:jpg|jpeg|gif|png|ico|cur|gz|svg|mp4|ogg|ogv|webm|htc)$ {
    add_header Cache-Control "max-age=2592000";
    access_log off;
}
location ~* \.(?:css|js)$ {
    add_header Cache-Control "max-age=31536000";
    access_log off;
}
location ~* \.(?:ttf|ttc|otf|eot|woff|woff2)$ {
    add_header Cache-Control "max-age=2592000";
    access_log off;
}
