server {
    listen 80;
    listen [::]:80;
    server_name *.freeflarum.com *.flarum.cloud;

    return 301 https://$host$request_uri;
}

map $ssl_server_name $cert_name {
    ~^(.+\.)?freeflarum\.com$ freeflarum.com;
    ~^(.+\.)?flarum\.cloud$    flarum.cloud;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    # TODO: automatic parent domain enumeration
    # TODO: inject index.php guard that redirects to correct parent domain?
    server_name ~^(?<tag>.+?)\.(freeflarum\.com|flarum\.cloud)$;

    ssl_certificate /etc/ssl/cloudflare/_wildcard.$cert_name.pem;
    ssl_certificate_key /etc/ssl/cloudflare/_wildcard.$cert_name.key;
    include /etc/nginx/snippets/ssl-params.conf;

    root /srv/host/$tag/public;
    index index.php index.html;

    include /etc/nginx/snippets/security-headers.conf;

    access_log /srv/host/$tag/logs/access.log;
    error_log /srv/host/$tag/logs/error.log;

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass unix:/var/run/php/php-fpm.$tag.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        try_files $fastcgi_script_name =404;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # TODO: deny .well-known?
}
