---
- name: Setup common skeleton app structure
  ansible.builtin.include_tasks: ./_common.yml
  vars:
      skeleton_root_dir: "{{ paths.tenants.flarum_skeleton }}"
  tags: ["skeleton", "flarum"]

- name: Sync Flarum skeleton
  ansible.builtin.include_tasks: ./_sync_archive.yml
  vars:
      archive_url: "https://github.com/no-cost/flarum-multitenant/archive/refs/heads/main.tar.gz"
      sync_dest: "{{ paths.tenants.flarum_skeleton }}/app"
  tags: ["skeleton", "flarum"]

- name: Upgrade all Flarum forums
  ansible.builtin.command:
      cmd: "{{ paths.backend_bin_root }}/upgrade_site -s flarum"
      chdir: "{{ paths.backend_root }}"
  become: true
  become_user: nocost
  changed_when: false
  async: 3600
  poll: 0
  tags: [never, "flarum-upgrade"]
