---
- name: Setup common skeleton app structure
  ansible.builtin.include_tasks: ./_common.yml
  vars:
      skeleton_root_dir: "{{ paths.tenants.mediawiki_skeleton }}"
  tags: ["skeleton", "mediawiki"]

- name: Install MediaWiki dependencies
  ansible.builtin.apt:
      name:
          - imagemagick
          - diffutils
      state: present
      update_cache: true
  tags: ["skeleton", "mediawiki"]

- name: Ensure hardlink for MediaWiki diff3 binary
  ansible.builtin.file:
      src: "{{ mw_hardlink.src }}"
      dest: "{{ mw_hardlink.dest }}"
      state: hard
      force: true
      owner: root
      group: root
      mode: "755"
  loop:
      - src: "/usr/bin/diff3"
        dest: "{{ paths.tenants.mediawiki_skeleton }}/usr/bin/diff3"
  loop_control:
      loop_var: mw_hardlink
  tags: ["skeleton", "chroot", "mediawiki"]

- name: Ensure hardlink for ImageMagick binary
  ansible.builtin.file:
      src: "/usr/bin/convert-im6.q16"
      dest: "{{ paths.tenants.mediawiki_skeleton }}/usr/bin/convert"
      state: hard
      mode: "0755"
      owner: root
      group: root
  tags: ["skeleton", "mediawiki"]

- name: Recursively hardlink ImageMagick configuration into skeleton
  ansible.posix.synchronize:
      src: /etc/ImageMagick-6/
      dest: "{{ paths.tenants.mediawiki_skeleton }}/etc/ImageMagick-6"
      rsync_opts:
          - "--link-dest=/etc/ImageMagick-6"
  delegate_to: "{{ inventory_hostname }}"
  tags: ["skeleton", "chroot", "mediawiki"]

- name: Sync MediaWiki skeleton
  ansible.builtin.include_tasks: ./_sync_archive.yml
  vars:
      archive_url: "https://github.com/no-cost/mediawiki-multitenant/archive/refs/heads/main.tar.gz"
      sync_dest: "{{ paths.tenants.mediawiki_skeleton }}/app/public"
  tags: ["skeleton", "mediawiki"]

- name: Write secrets.php file
  ansible.builtin.template:
      src: files/srv/skeleton/mediawiki/secrets.php
      dest: "{{ paths.tenants.mediawiki_skeleton }}/app/public/secrets.php"
      owner: "www-data"
      group: "www-data"
      mode: "0644"
  tags: ["skeleton", "mediawiki"]

- name: Upgrade all MediaWiki sites
  ansible.builtin.command:
      cmd: "{{ paths.backend_bin_root }}/upgrade_site -s mediawiki"
      chdir: "{{ paths.backend_root }}"
  become: true
  become_user: nocost
  changed_when: false
  async: 3600
  poll: 0
  tags: [never, "upgrade"]
