---
- name: Setup common skeleton app structure
  ansible.builtin.include_tasks: ./_common.yml
  vars:
      skeleton_root_dir: "{{ paths.tenants.mediawiki_skeleton }}"
  tags: ["skeleton", "mediawiki"]

- name: Install MediaWiki dependencies
  ansible.builtin.apt:
      name:
          - imagemagick
          - diffutils
      state: present
      update_cache: true
  tags: ["skeleton", "mediawiki"]

- name: Create hardlink for MediaWiki diff3 binary
  ansible.builtin.file:
      src: "{{ mw_hardlink.src }}"
      dest: "{{ mw_hardlink.dest }}"
      state: hard
      force: true
      owner: root
      group: root
      mode: "755"
  loop:
      - src: "/usr/bin/diff3"
        dest: "{{ paths.tenants.mediawiki_skeleton }}/usr/bin/diff3"
  loop_control:
      loop_var: mw_hardlink
  tags: ["skeleton", "chroot", "mediawiki"]

- name: Create hardlink for ImageMagick binary
  ansible.builtin.file:
      src: "/usr/bin/convert-im6.q16"
      dest: "{{ paths.tenants.mediawiki_skeleton }}/usr/bin/convert"
      state: hard
      mode: "0755"
      owner: root
      group: root
  tags: ["skeleton", "mediawiki"]

- name: Hardlink shared library dependencies for chroot binaries
  ansible.builtin.include_tasks: ./_hardlink_libs.yml
  vars:
      skeleton_root_dir: "{{ paths.tenants.mediawiki_skeleton }}"
      lib_paths:
          - "/lib/aarch64-linux-gnu/libbrotlicommon.so.1"
          - "/lib/aarch64-linux-gnu/libbrotlidec.so.1"
          - "/lib/aarch64-linux-gnu/libbsd.so.0"
          - "/lib/aarch64-linux-gnu/libbz2.so.1.0"
          - "/lib/aarch64-linux-gnu/libc.so.6"
          - "/lib/aarch64-linux-gnu/libexpat.so.1"
          - "/lib/aarch64-linux-gnu/libfftw3.so.3"
          - "/lib/aarch64-linux-gnu/libfontconfig.so.1"
          - "/lib/aarch64-linux-gnu/libfreetype.so.6"
          - "/lib/aarch64-linux-gnu/libgcc_s.so.1"
          - "/lib/aarch64-linux-gnu/libglib-2.0.so.0"
          - "/lib/aarch64-linux-gnu/libgomp.so.1"
          - "/lib/aarch64-linux-gnu/libicudata.so.74"
          - "/lib/aarch64-linux-gnu/libicuuc.so.74"
          - "/lib/aarch64-linux-gnu/liblcms2.so.2"
          - "/lib/aarch64-linux-gnu/liblqr-1.so.0"
          - "/lib/aarch64-linux-gnu/libltdl.so.7"
          - "/lib/aarch64-linux-gnu/liblzma.so.5"
          - "/lib/aarch64-linux-gnu/libm.so.6"
          - "/lib/aarch64-linux-gnu/libMagickCore-6.Q16.so.7"
          - "/lib/aarch64-linux-gnu/libMagickWand-6.Q16.so.7"
          - "/lib/aarch64-linux-gnu/libmd.so.0"
          - "/lib/aarch64-linux-gnu/libpcre2-8.so.0"
          - "/lib/aarch64-linux-gnu/libpng16.so.16"
          - "/lib/aarch64-linux-gnu/libstdc++.so.6"
          - "/lib/aarch64-linux-gnu/libX11.so.6"
          - "/lib/aarch64-linux-gnu/libXau.so.6"
          - "/lib/aarch64-linux-gnu/libxcb.so.1"
          - "/lib/aarch64-linux-gnu/libXdmcp.so.6"
          - "/lib/aarch64-linux-gnu/libXext.so.6"
          - "/lib/aarch64-linux-gnu/libxml2.so.2"
          - "/lib/aarch64-linux-gnu/libz.so.1"
  tags: ["skeleton", "chroot", "mediawiki"]

- name: Ensure public dir
  ansible.builtin.file:
      path: "{{ paths.tenants.mediawiki_skeleton }}/app/public"
      state: directory
      owner: "www-data"
      group: "www-data"
      mode: "0775"
  tags: ["skeleton", "mediawiki"]

- name: Unarchive Mediawiki
  ansible.builtin.unarchive:
      src: "https://github.com/no-cost/mediawiki-multitenant/archive/refs/heads/main.tar.gz"
      dest: "{{ paths.tenants.mediawiki_skeleton }}/app/public"
      remote_src: true
      owner: www-data
      group: www-data
      mode: "0775"
      extra_opts: ["--strip-components=1"] # strip root version folder
  tags: ["skeleton", "mediawiki"]

- name: Write secrets.php file
  ansible.builtin.template:
      src: files/srv/skeleton/mediawiki/secrets.php
      dest: "{{ paths.tenants.mediawiki_skeleton }}/app/public/secrets.php"
      owner: "www-data"
      group: "www-data"
      mode: "0644"
  tags: ["skeleton", "mediawiki"]

- name: Upgrade all MediaWiki sites
  ansible.builtin.command:
      cmd: "{{ paths.backend_bin_root }}/upgrade-site -s mediawiki"
      chdir: "{{ paths.backend_root }}"
  become: true
  become_user: nocost
  changed_when: false
  tags: ["upgrade"]
