---
- name: Setup common skeleton app structure
  ansible.builtin.include_tasks: ./_common.yml
  vars:
      skeleton_root_dir: "{{ paths.tenants.wordpress_skeleton }}"
  tags: ["skeleton", "wordpress"]

- name: Install WP-CLI system-wide
  ansible.builtin.get_url:
      url: "https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar"
      dest: "/usr/bin/wp"
      owner: root
      group: root
      mode: "755"
  tags: ["skeleton", "wordpress"]

- name: Ensure public dir
  ansible.builtin.file:
      path: "{{ paths.tenants.wordpress_skeleton }}/app/public"
      state: directory
      owner: "www-data"
      group: "www-data"
      mode: "775"
  tags: ["skeleton", "wordpress"]

# https://developer.wordpress.org/cli/commands/core/download/
- name: Unarchive WordPress
  ansible.builtin.unarchive:
      src: "https://github.com/no-cost/wordpress-multitenant/archive/refs/heads/main.tar.gz"
      dest: "{{ paths.tenants.wordpress_skeleton }}/app/public"
      remote_src: true
      owner: www-data
      group: www-data
      mode: "0775"
      extra_opts: ["--strip-components=1"] # strip root version folder
  tags: ["skeleton", "wordpress"]

- name: Write secrets.php file
  ansible.builtin.template:
      src: files/srv/skeleton/wordpress/secrets.php
      dest: "{{ paths.tenants.wordpress_skeleton }}/app/public/secrets.php"
      owner: "www-data"
      group: "www-data"
      mode: "0644"
  tags: ["skeleton", "wordpress"]
