---
- name: Setup common skeleton app structure
  ansible.builtin.include_tasks: ./helpers/common.yml
  vars:
      skeleton_root_dir: "{{ paths.tenants.wordpress_skeleton }}"
  tags: ["skeleton", "wordpress"]

- name: Install WP-CLI system-wide
  ansible.builtin.get_url:
      url: "https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar"
      dest: "/usr/bin/wp"
      owner: root
      group: root
      mode: "755"
  tags: ["skeleton", "wordpress"]

- name: Ensure public dir
  ansible.builtin.file:
      path: "{{ paths.tenants.wordpress_skeleton }}/app/public"
      state: directory
      owner: "www-data"
      group: "www-data"
      mode: "775"
  tags: ["skeleton", "wordpress"]

# https://developer.wordpress.org/cli/commands/core/download/
- name: Download WordPress core using WP-CLI
  ansible.builtin.command:
      cmd: "wp core download"
      chdir: "{{ paths.tenants.wordpress_skeleton }}/app/public"
      creates: "{{ paths.tenants.wordpress_skeleton }}/app/public/wp-config-sample.php"
  become: true
  become_user: "www-data"
  tags: ["skeleton", "wordpress"]

- name: Create mu-plugins directory in skeleton
  ansible.builtin.file:
      path: "{{ paths.tenants.wordpress_skeleton }}/app/public/wp-content/mu-plugins"
      state: directory
      owner: "www-data"
      group: "www-data"
      mode: "775"
  tags: ["skeleton", "wordpress"]

- name: Deploy SMTP mu-plugin to skeleton
  ansible.builtin.template:
      src: files/srv/skeleton/wordpress/mu-plugins/smtp.php
      dest: "{{ paths.tenants.wordpress_skeleton }}/app/public/wp-content/mu-plugins/smtp.php"
      owner: "www-data"
      group: "www-data"
      mode: "644"
  tags: ["skeleton", "wordpress"]
# HACK: is there a better way?
#- name: Symlink wp-config of skeleton tenant to skeleton template, so wp-cli doesn't complain
#  ansible.builtin.file:
#      src: "{{ paths.tenants.root }}/wordpress_skeleton/app/wp-config.php"
#      dest: "{{ paths.tenants.wordpress_skeleton }}/wp-config.php"
#      state: link
#      owner: "www-data"
#      group: "www-data"
#      force: true
#  tags: ["skeleton", "wordpress"]
