local-address=127.0.0.1
local-port=53
allow-from=127.0.0.0/8, ::1/128
query-local-address=0.0.0.0, ::
max-recursion-depth=40

dnssec=validate
dnssec-log-bogus=yes
log-common-errors=no
quiet=yes

setgid=pdns
setuid=pdns
threads=1
max-cache-entries=10000
max-packetcache-entries=5000
