---
- name: restart nginx
  ansible.builtin.systemd:
      name: nginx
      state: restarted
      daemon_reload: true

- name: reload nginx
  ansible.builtin.systemd:
      name: nginx
      state: reloaded

- name: restart php-fpm
  ansible.builtin.systemd:
      name: "php{{ php_version }}-fpm"
      state: restarted
      daemon_reload: true

- name: reload php-fpm
  ansible.builtin.systemd:
      name: "php{{ php_version }}-fpm"
      state: reloaded

- name: restart mariadb
  ansible.builtin.systemd:
      name: mariadb
      state: restarted
      daemon_reload: true

- name: restart pdns-recursor
  ansible.builtin.systemd:
      name: pdns-recursor
      state: restarted

- name: restart postfix
  ansible.builtin.systemd:
      name: postfix
      state: restarted

- name: restart opendkim
  ansible.builtin.systemd:
      name: opendkim
      state: restarted

- name: restart spamassassin
  ansible.builtin.systemd:
      name: "{{ 'spamassassin' if ansible_distribution == 'Ubuntu' and ansible_distribution_version is version('24.04', '<') else 'spamd' }}"
      state: restarted

- name: restart postgrey
  ansible.builtin.systemd:
      name: postgrey
      state: restarted

- name: restart fail2ban
  ansible.builtin.systemd:
      name: fail2ban
      state: restarted

- name: restart sshd
  ansible.builtin.systemd:
      name: ssh
      state: restarted

- name: restart chrony
  ansible.builtin.systemd:
      name: chrony
      state: restarted

- name: restart sysstat
  ansible.builtin.systemd:
      name: sysstat
      state: restarted

- name: restart nocost-backend
  ansible.builtin.systemd:
      name: nocost-backend
      state: restarted
      daemon_reload: true

- name: daemon reload
  ansible.builtin.systemd:
      daemon_reload: true

- name: postmap postfix_virtual
  ansible.builtin.command:
      cmd: postmap /etc/postfix/virtual

- name: postmap postfix_sender_access
  ansible.builtin.command:
      cmd: postmap /etc/postfix/sender_access

- name: restart monit
  ansible.builtin.systemd:
      name: monit
      state: restarted
      daemon_reload: true
