---
- name: Deploy FreeFlarum
  hosts: all

  vars_files:
      # base vars
      - "../public_vars.prod.yml"
      - "../public_vars.{{ env | default('dev') }}.yml"
      # is automatically decrypted, see `ansible.cfg`'s `vault_password_file`:
      - "../secret_vars.prod.yml"
      - "../secret_vars.{{ env | default('dev') }}.yml"

  handlers:
      - name: Import handlers
        ansible.builtin.import_tasks: handlers.yml

  tasks:
      - name: Packages
        ansible.builtin.include_tasks: tasks/00-base-packages.yml
        tags: [always]

      - name: Base system
        ansible.builtin.include_tasks: tasks/01-base-system.yml
        tags: [always]

      - name: Security
        ansible.builtin.include_tasks: tasks/02-security.yml
        tags: [always]

      - name: SSL
        ansible.builtin.include_tasks: tasks/03-ssl.yml
        tags: [always]

      - name: Nginx
        ansible.builtin.include_tasks: tasks/04-nginx.yml
        tags: [always]

      - name: PHP-FPM
        ansible.builtin.include_tasks: tasks/05-php-fpm.yml
        tags: [always]

      - name: MariaDB
        ansible.builtin.include_tasks: tasks/06-mariadb.yml
        tags: [always]

      - name: Python
        ansible.builtin.include_tasks: tasks/07-python.yml
        tags: [always]

      - name: Postfix
        ansible.builtin.include_tasks: tasks/08-postfix.yml
        tags: [always]

      - name: Deploy freeflarum-backend
        ansible.builtin.include_tasks: tasks/09-freeflarum-backend.yml
        tags: [always]

      - name: Skeletons
        ansible.builtin.include_tasks: tasks/10-skeletons.yml
        tags: [always]

      - name: Cron
        ansible.builtin.include_tasks: tasks/11-cron.yml
        tags: [always]

      - name: Monitoring
        ansible.builtin.include_tasks: tasks/12-monitoring.yml
        tags: [always]
