---
- name: Deploy FreeFlarum
  hosts: all
  gather_facts: false
  become: false

  vars_files:
    - "public_vars.{{ environment | default('dev') }}.yml"
    # is automatically decrypted, see `ansible.cfg`'s `vault_password_file`:
    - "secret_vars.{{ environment | default('dev') }}.yml"

  handlers:
    - name: Import handlers
      ansible.builtin.import_tasks: handlers.yml

  tasks:
    - name: Packages
      ansible.builtin.include_tasks: tasks/00-base-packages.yml
      tags: [base, system]

    - name: Base system
      ansible.builtin.include_tasks: tasks/01-base-system.yml
      tags: [base, system]

    - name: Security
      ansible.builtin.include_tasks: tasks/02-security.yml
      tags: [security]

    - name: Nginx
      ansible.builtin.include_tasks: tasks/03-nginx.yml
      tags: [nginx, web]

    - name: PHP-FPM
      ansible.builtin.include_tasks: tasks/04-php-fpm.yml
      tags: [php, php-fpm]

    - name: MariaDB
      ansible.builtin.include_tasks: tasks/05-mariadb.yml
      tags: [mariadb, database]

    - name: Python
      ansible.builtin.include_tasks: tasks/06-python.yml
      tags: [python, mainsite]

    - name: Chroot
      ansible.builtin.include_tasks: tasks/07-chroot.yml
      tags: [chroot, security]

    - name: SSL
      ansible.builtin.include_tasks: tasks/08-ssl.yml
      tags: [ssl, certificates]

    - name: Postfix
      ansible.builtin.include_tasks: tasks/09-postfix.yml
      tags: [mail, postfix]

    - name: Backup
      ansible.builtin.include_tasks: tasks/10-backup.yml
      tags: [backup]

    - name: Monitoring
      ansible.builtin.include_tasks: tasks/11-monitoring.yml
      tags: [monitoring]

    - name: Deploy freeflarum-backend
      ansible.builtin.include_tasks: tasks/12-freeflarum-backend.yml
      tags: [freeflarum, backend, deploy]

    - name: Cron
      ansible.builtin.include_tasks: tasks/13-cron.yml
      tags: [cron]
