---
- name: Provision new tenant
  hosts: all
  vars_files:
      - "../public_vars.prod.yml"
      - "../public_vars.{{ env | default('dev') }}.yml"

  vars_prompt:
      - name: tenant_tag
        prompt: "Enter tenant tag (unique ID)"
        private: false

      - name: service_type
        prompt: "Enter service type (`flarum` / `wordpress` / `mediawiki`)"
        private: false

      - name: tenant_admin_email
        prompt: "Enter tenant admin's e-mail (used to send password reset e-mail)"
        private: false

      - name: tenant_admin_password
        prompt: "Enter tenant admin password"
        private: true

      - name: tenant_db_password
        prompt: "Enter tenant DB password"
        private: true

  tasks:
      - name: Include tenant provisioning tasks
        ansible.builtin.include_tasks: ./tasks/tenants/provision-main.yml
        tags: [always]
